import type { Question } from '../../engine/model';

// Stage 3 transfer questions: the concepts of each breadth mission, in different stories.
// Every option explains itself.
export const STAGE3_QUESTIONS: Question[] = [
  // ----- The Region went dark (DR strategies) -----
  {
    id: 'q-dr-1',
    domain: 'resilient',
    concepts: ['dr-strategies'],
    difficulty: 2,
    stem: 'A company runs a web application on EC2 instances behind an Application Load Balancer with an Amazon RDS for PostgreSQL database in us-east-1. The DR requirements are an RPO of 15 minutes and an RTO of 1 hour in us-west-2. Leadership wants the lowest ongoing cost that meets these objectives. Which approach should a solutions architect recommend?',
    options: [
      { id: 'a', text: 'Create a cross-Region read replica in us-west-2, and keep an Auto Scaling group and load balancer there with the desired capacity set to zero until a disaster.', why: 'Correct. This is pilot light: continuous replication meets the 15-minute RPO, and promoting the replica and launching the fleet fits within an hour while almost nothing runs day to day.' },
      { id: 'b', text: 'Take daily automated snapshots and copy them to us-west-2.', why: 'Backup and restore is cheapest, but a daily copy means up to 24 hours of lost data: far beyond a 15-minute RPO.' },
      { id: 'c', text: 'Run a full-size copy of the application in us-west-2 behind Route 53 latency-based routing.', why: 'Multi-site meets the objectives easily but doubles the cost; the requirement asks for the lowest cost that meets them.' },
      { id: 'd', text: 'Convert the database to a Multi-AZ deployment.', why: 'Multi-AZ protects against losing an Availability Zone, not the whole Region.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-dr-2',
    domain: 'resilient',
    concepts: ['route53-routing-policies'],
    difficulty: 2,
    stem: 'An application has an active stack in eu-west-1 and a standby stack in eu-central-1, each behind an Application Load Balancer. Users must be sent to eu-central-1 automatically only when eu-west-1 becomes unhealthy. Which Route 53 configuration meets this requirement?',
    options: [
      { id: 'a', text: 'Failover routing with the eu-west-1 record as primary and the eu-central-1 record as secondary, with Evaluate Target Health or health checks on the primary.', why: 'Correct. Failover routing answers with the primary while it is healthy and switches to the secondary when its health check fails.' },
      { id: 'b', text: 'Simple routing with both load balancers as values in one record.', why: 'Simple routing has no health checks: clients get both answers and can keep using the failed Region.' },
      { id: 'c', text: 'Weighted routing with weights of 100 and 0 and no health checks.', why: 'Without health checks Route 53 never notices the failure, so it keeps returning the 100-weight record.' },
      { id: 'd', text: 'Geolocation routing with Europe mapped to eu-west-1.', why: 'Geolocation routes by user location, not health. All European users would still go to eu-west-1.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-dr-3',
    domain: 'resilient',
    concepts: ['aurora-global', 'dr-strategies'],
    difficulty: 2,
    stem: 'A trading platform uses Amazon Aurora MySQL. The business requires the database to survive a Regional outage with an RPO of about 1 second and an RTO of about 1 minute. Which solution meets these requirements?',
    options: [
      { id: 'a', text: 'Aurora Global Database with a secondary cluster in another Region.', why: 'Correct. Storage-level replication typically lags under a second, and a secondary cluster can be promoted in about a minute.' },
      { id: 'b', text: 'Add Aurora Replicas in two more Availability Zones.', why: 'Aurora Replicas stay in the same Region, so a Regional outage takes them down too.' },
      { id: 'c', text: 'Enable automated backups and copy snapshots to another Region every hour.', why: 'An hourly copy gives an RPO of up to an hour, and restoring a snapshot takes far longer than a minute.' },
      { id: 'd', text: 'Use AWS DMS to replicate to an Aurora cluster in another Region.', why: 'DMS can replicate across Regions, but with more lag and operational effort, and failover is not a managed one-minute promotion.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-dr-4',
    domain: 'resilient',
    concepts: ['dr-strategies', 'aws-backup'],
    difficulty: 1,
    stem: 'A company keeps internal reporting tools that can be offline for up to 24 hours after a disaster and can lose up to a day of data. The company wants the least expensive DR strategy. What should a solutions architect recommend?',
    options: [
      { id: 'a', text: 'Backup and restore: daily backups copied to another Region with AWS Backup, restored when needed.', why: 'Correct. With an RTO and RPO of a day, nothing needs to run in the DR Region; backups are the cheapest option.' },
      { id: 'b', text: 'Pilot light with a cross-Region read replica.', why: 'It works, but it pays for a running replica that a 24-hour RPO doesn\'t require.' },
      { id: 'c', text: 'Warm standby with a scaled-down copy of the stack.', why: 'Running servers all year is far more than these objectives need.' },
      { id: 'd', text: 'Multi-site active/active.', why: 'The most expensive strategy, for objectives that tolerate a full day.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-dr-5',
    domain: 'resilient',
    concepts: ['dr-strategies'],
    difficulty: 3,
    stem: 'A company runs a scaled-down but fully functional copy of its production environment in a second Region, with the database replicating continuously. During failover the copy scales out to full capacity. Which DR strategy is this, and what mainly determines its RTO?',
    options: [
      { id: 'a', text: 'Warm standby; DNS failover time plus the time to scale out the running fleet.', why: 'Correct. Warm standby already serves at reduced capacity, so recovery is the DNS switch plus scaling out.' },
      { id: 'b', text: 'Pilot light; the time to launch the application servers from AMIs.', why: 'In pilot light the application tier is switched off. Here it is running, just smaller.' },
      { id: 'c', text: 'Backup and restore; the time to restore the database.', why: 'The database replicates continuously; nothing is restored from backup.' },
      { id: 'd', text: 'Multi-site; there is no recovery time.', why: 'Multi-site runs full capacity in both Regions and serves traffic from both. This copy is scaled down.' },
    ],
    correct: ['a'],
  },

  // ----- Lag on the leaderboard (global tables, DAX, latency routing) -----
  {
    id: 'q-lb-1',
    domain: 'performant',
    concepts: ['dynamodb-global-tables'],
    difficulty: 2,
    stem: 'A social app stores user profiles in an Amazon DynamoDB table in us-east-1. Users in Europe and Asia complain that saving profile changes is slow. The app must offer low-latency reads and writes on all three continents. Which solution meets these requirements?',
    options: [
      { id: 'a', text: 'Convert the table to a DynamoDB global table with replicas in Europe and Asia, and deploy the application in those Regions.', why: 'Correct. Every global table replica accepts reads and writes locally and replicates to the others.' },
      { id: 'b', text: 'Add a DAX cluster in us-east-1.', why: 'DAX speeds up reads in the same Region; writes from Europe and Asia still cross an ocean.' },
      { id: 'c', text: 'Put Amazon CloudFront in front of the API.', why: 'CloudFront caches responses; profile writes still go to us-east-1.' },
      { id: 'd', text: 'Switch the table to on-demand capacity.', why: 'Capacity mode doesn\'t change the distance between users and the table.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-lb-2',
    domain: 'performant',
    concepts: ['dax'],
    difficulty: 2,
    stem: 'A sports app reads the same live-score item from a DynamoDB table tens of thousands of times per second. Requests are throttled even with on-demand capacity. Which change resolves the throttling with the least change to the application code?',
    options: [
      { id: 'a', text: 'Add DynamoDB Accelerator (DAX) and point the DynamoDB SDK client at the DAX cluster.', why: 'Correct. DAX is API-compatible and serves the hot item from memory, so the partition no longer sees every read.' },
      { id: 'b', text: 'Switch to provisioned capacity with a higher read capacity.', why: 'A single item lives in one partition, which is capped at 3,000 RCU no matter how much table capacity you buy.' },
      { id: 'c', text: 'Add a global secondary index on the score attribute.', why: 'The reads still target the same item; an index doesn\'t spread one hot key.' },
      { id: 'd', text: 'Use strongly consistent reads.', why: 'Strongly consistent reads cost twice as much capacity and bypass DAX; they make throttling worse.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-lb-3',
    domain: 'performant',
    concepts: ['route53-routing-policies'],
    difficulty: 1,
    stem: 'A company deploys the same API in us-east-1, eu-west-1 and ap-southeast-2. Each user should be served by the Region that gives them the lowest network latency, and an unhealthy Region should stop receiving traffic. Which Route 53 routing policy should be used?',
    options: [
      { id: 'a', text: 'Latency-based routing with health checks on each record.', why: 'Correct. Route 53 answers with the healthy Region that has the lowest measured latency for the user\'s resolver.' },
      { id: 'b', text: 'Geolocation routing.', why: 'Geolocation routes by where users are, not by measured latency; it is for compliance or localisation.' },
      { id: 'c', text: 'Weighted routing with equal weights.', why: 'Equal weights spread users randomly across Regions, many of them far away.' },
      { id: 'd', text: 'Multivalue answer routing.', why: 'It returns several healthy answers at random, not the closest one.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-lb-4',
    domain: 'resilient',
    concepts: ['dynamodb-global-tables', 'route53-routing-policies'],
    difficulty: 2,
    stem: 'A multiplayer game uses a DynamoDB global table in three Regions and Route 53 latency routing to API Gateway in each Region. During a test, eu-west-1 was taken offline but European players kept receiving errors for hours. What is the MOST likely cause?',
    options: [
      { id: 'a', text: 'The latency records had no health checks, so Route 53 kept returning the eu-west-1 endpoint.', why: 'Correct. Without a health check a record never drops out, whatever its routing policy.' },
      { id: 'b', text: 'Global tables must be promoted manually in the surviving Region.', why: 'Every global table replica already accepts writes; there is nothing to promote.' },
      { id: 'c', text: 'The table needed DAX in each Region.', why: 'DAX is a read cache; it has no effect on where Route 53 sends users.' },
      { id: 'd', text: 'The DNS TTL was 60 seconds.', why: 'A 60-second TTL delays failover by about a minute, not hours.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-lb-5',
    domain: 'performant',
    concepts: ['dax', 'dynamodb-capacity'],
    difficulty: 2,
    stem: 'Which TWO statements about DynamoDB Accelerator (DAX) are correct? (Select TWO.)',
    options: [
      { id: 'a', text: 'DAX can return cached reads in microseconds.', why: 'Correct. It is an in-memory cache in front of the table.' },
      { id: 'b', text: 'Applications use a DAX client that is API-compatible with DynamoDB.', why: 'Correct. Few code changes are needed: the calls stay the same.' },
      { id: 'c', text: 'DAX makes write-heavy workloads faster.', why: 'DAX is write-through: every write still goes to the table. It accelerates reads.' },
      { id: 'd', text: 'DAX serves strongly consistent reads from its cache.', why: 'Strongly consistent reads are passed through to DynamoDB.' },
      { id: 'e', text: 'DAX replicates data to other Regions.', why: 'Cross-Region replication is global tables; DAX is a cluster in one Region.' },
    ],
    correct: ['a', 'b'],
  },

  // ----- Payroll by Friday (VPN, Direct Connect) -----
  {
    id: 'q-bo-1',
    domain: 'secure',
    concepts: ['site-to-site-vpn', 'hybrid-connectivity'],
    difficulty: 1,
    stem: 'A company must connect its head office to a VPC by tomorrow so staff can reach an internal application. Traffic must be encrypted. Which solution meets these requirements?',
    options: [
      { id: 'a', text: 'Create a virtual private gateway, a customer gateway and a Site-to-Site VPN connection.', why: 'Correct. A VPN runs over the existing internet connection, is encrypted, and is up in minutes.' },
      { id: 'b', text: 'Order an AWS Direct Connect dedicated connection.', why: 'New Direct Connect connections take weeks to provision, and they are not encrypted by default.' },
      { id: 'c', text: 'Create a VPC peering connection to the office network.', why: 'Peering connects VPCs to VPCs, not to on-premises networks.' },
      { id: 'd', text: 'Give the application a public IP and restrict its security group to the office IP.', why: 'That exposes the app to the internet and doesn\'t encrypt anything by itself.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-bo-2',
    domain: 'performant',
    concepts: ['direct-connect'],
    difficulty: 1,
    stem: 'A media company transfers large files between its data centre and AWS every night. Transfers over the internet VPN vary widely in speed and often miss the window. The company needs consistent network performance. What should a solutions architect recommend?',
    options: [
      { id: 'a', text: 'AWS Direct Connect.', why: 'Correct. A dedicated private connection gives consistent bandwidth and latency that the internet cannot.' },
      { id: 'b', text: 'A second Site-to-Site VPN connection.', why: 'Both VPNs still ride the internet, with the same unpredictability.' },
      { id: 'c', text: 'S3 Transfer Acceleration.', why: 'It speeds up long-distance uploads to S3 over the internet, but performance is still not dedicated or consistent.' },
      { id: 'd', text: 'AWS Client VPN.', why: 'Client VPN connects individual users\' devices, not a data centre.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-bo-3',
    domain: 'secure',
    concepts: ['direct-connect', 'site-to-site-vpn'],
    difficulty: 2,
    stem: 'A bank uses a 1 Gbps AWS Direct Connect connection. Auditors require all traffic between the data centre and the VPC to be encrypted in transit. Which solution meets the requirement?',
    options: [
      { id: 'a', text: 'Establish an IPsec Site-to-Site VPN over the Direct Connect connection (using a public or transit virtual interface).', why: 'Correct. The VPN encrypts traffic while Direct Connect still provides the private, consistent path.' },
      { id: 'b', text: 'Rely on Direct Connect, because it is a private connection.', why: 'Private is not encrypted: Direct Connect carries traffic in clear text by default.' },
      { id: 'c', text: 'Enable MACsec on the 1 Gbps connection.', why: 'MACsec is available on 10 Gbps and 100 Gbps dedicated connections, not 1 Gbps.' },
      { id: 'd', text: 'Encrypt the EBS volumes of the instances.', why: 'That is encryption at rest; the requirement is encryption in transit.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-bo-4',
    domain: 'resilient',
    concepts: ['hybrid-connectivity', 'site-to-site-vpn'],
    difficulty: 2,
    stem: 'A company relies on a single Direct Connect connection for hybrid traffic. It wants a backup path if the connection fails, at the lowest cost. What should a solutions architect do?',
    options: [
      { id: 'a', text: 'Add a Site-to-Site VPN on the same virtual private gateway as a backup.', why: 'Correct. BGP prefers the Direct Connect routes and fails over to the VPN when DX goes down; a VPN costs a few dozen dollars a month.' },
      { id: 'b', text: 'Order a second Direct Connect connection at a different location.', why: 'That is the maximum-resiliency design, not the lowest-cost backup.' },
      { id: 'c', text: 'Create a VPC peering connection.', why: 'Peering doesn\'t connect to on-premises networks.' },
      { id: 'd', text: 'Use a NAT gateway for traffic to the data centre.', why: 'NAT gateways provide outbound internet access, not a private path to on-premises.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-bo-5',
    domain: 'secure',
    concepts: ['route-blackholes', 'site-to-site-vpn'],
    difficulty: 2,
    stem: 'A Site-to-Site VPN shows both tunnels UP. On-premises users can\'t reach an EC2 instance in a private subnet, although the security group allows their CIDR. What is the MOST likely missing piece?',
    options: [
      { id: 'a', text: 'A route in the subnet\'s route table for the on-premises CIDR pointing to the virtual private gateway (or route propagation).', why: 'Correct. Without it, responses from the instance have no way back to the data centre.' },
      { id: 'b', text: 'An internet gateway attached to the VPC.', why: 'VPN traffic doesn\'t use the internet gateway.' },
      { id: 'c', text: 'An outbound security group rule for the response traffic.', why: 'Security groups are stateful: responses to allowed inbound traffic are allowed automatically.' },
      { id: 'd', text: 'A NAT gateway in the private subnet.', why: 'NAT is for outbound internet access, not for routing to on-premises.' },
    ],
    correct: ['a'],
  },

  // ----- Spaghetti peering (Transit Gateway) -----
  {
    id: 'q-tg-1',
    domain: 'performant',
    concepts: ['transit-gateway', 'vpc-peering'],
    difficulty: 1,
    stem: 'A company has 40 VPCs across several accounts and an on-premises data centre connected by VPN. Managing peering connections and routes has become error-prone. Which solution simplifies connectivity with the LEAST operational overhead?',
    options: [
      { id: 'a', text: 'Create a transit gateway, attach every VPC and the VPN, and share it with the other accounts through AWS RAM.', why: 'Correct. A hub-and-spoke transit gateway replaces the mesh, and transitive routing through it includes the VPN.' },
      { id: 'b', text: 'Create a full mesh of VPC peering connections.', why: '40 VPCs need 780 peering connections, and peered VPCs still can\'t use each other\'s VPN.' },
      { id: 'c', text: 'Create a VPN connection from each VPC to the data centre.', why: 'That only connects VPCs to on-premises, not to each other, and multiplies VPNs to manage.' },
      { id: 'd', text: 'Use AWS PrivateLink between every pair of VPCs.', why: 'PrivateLink exposes individual services, not full network connectivity, and still scales per pair.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-tg-2',
    domain: 'performant',
    concepts: ['vpc-peering'],
    difficulty: 2,
    stem: 'VPC A is peered with VPC B, and VPC B is peered with VPC C. Routes and security groups are correct for each peering. An instance in VPC A can\'t reach an instance in VPC C. Why?',
    options: [
      { id: 'a', text: 'VPC peering is not transitive; A needs its own peering with C (or a transit gateway).', why: 'Correct. Traffic can\'t pass through VPC B to a third VPC.' },
      { id: 'b', text: 'Peering connections only work within one account.', why: 'Cross-account peering is supported.' },
      { id: 'c', text: 'VPC C needs an internet gateway.', why: 'Peering traffic doesn\'t use internet gateways.' },
      { id: 'd', text: 'Security groups can\'t reference peered VPCs.', why: 'They can reference SGs in a peered VPC in the same Region, and CIDR rules work anywhere; the routing is the problem.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-tg-3',
    domain: 'secure',
    concepts: ['transit-gateway'],
    difficulty: 3,
    stem: 'Production and development VPCs are attached to a transit gateway. Both must reach a shared-services VPC, but development must never reach production. What should a solutions architect configure?',
    options: [
      { id: 'a', text: 'Separate transit gateway route tables: associate prod and dev with their own tables, each with only shared-services routes propagated, and a shared-services table that has both.', why: 'Correct. Association decides which table an attachment uses; propagation decides which routes it contains. Dev\'s table simply has no route to prod.' },
      { id: 'b', text: 'Use the default transit gateway route table and block dev in the prod security groups.', why: 'With one table everything can route to everything; relying only on SGs leaves the network open.' },
      { id: 'c', text: 'Peer prod and dev to shared services instead.', why: 'It works because peering is non-transitive, but it gives up the transit gateway hub the company is scaling on.' },
      { id: 'd', text: 'Add a NACL deny rule in shared services.', why: 'That would block shared services, not the dev-to-prod path.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-tg-4',
    domain: 'secure',
    concepts: ['aws-organizations', 'transit-gateway'],
    difficulty: 1,
    stem: 'A networking account owns a transit gateway. VPCs in 15 other accounts in the same AWS Organization must attach to it. How should the transit gateway be made available to those accounts?',
    options: [
      { id: 'a', text: 'Share it with AWS Resource Access Manager (RAM).', why: 'Correct. RAM shares the transit gateway with accounts or the whole organization so they can create attachments.' },
      { id: 'b', text: 'Create a transit gateway in each account and peer them.', why: 'That multiplies hubs and costs for no benefit.' },
      { id: 'c', text: 'Use a service control policy that allows attachments.', why: 'SCPs only limit permissions; they don\'t share resources.' },
      { id: 'd', text: 'Use VPC sharing to move all VPCs into the networking account.', why: 'VPC sharing shares subnets, not a transit gateway, and doesn\'t connect existing VPCs.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-tg-5',
    domain: 'resilient',
    concepts: ['vpc-peering', 'hybrid-connectivity'],
    difficulty: 2,
    stem: 'A VPC with a Site-to-Site VPN to the data centre is peered with a second VPC. Instances in the second VPC can\'t reach on-premises servers, even after adding a route to the on-premises CIDR via the peering connection. What is the cause?',
    options: [
      { id: 'a', text: 'Peering doesn\'t support edge-to-edge routing: the second VPC can\'t use the first VPC\'s VPN.', why: 'Correct. A VPC never forwards traffic arriving over a peering connection on to its VPN, DX, IGW or NAT gateway. Use a transit gateway.' },
      { id: 'b', text: 'The VPN needs a second tunnel.', why: 'The second tunnel is for redundancy; it wouldn\'t make transitive routing work.' },
      { id: 'c', text: 'The peering connection must be in another Region.', why: 'Region makes no difference to edge-to-edge routing.' },
      { id: 'd', text: 'The on-premises firewall needs a rule for the second VPC.', why: 'Traffic never reaches the data centre: AWS drops it at the first VPC.' },
    ],
    correct: ['a'],
  },

  // ----- Seven years, no excuses (versioning, Object Lock, replication, backups) -----
  {
    id: 'q-iv-1',
    domain: 'secure',
    concepts: ['s3-object-lock'],
    difficulty: 1,
    stem: 'A brokerage must store trade confirmations in Amazon S3 in a WORM format for 6 years. No user, including the root user, may delete or overwrite them during that period. Which solution meets these requirements?',
    options: [
      { id: 'a', text: 'Enable S3 Object Lock in compliance mode with a 6-year default retention.', why: 'Correct. In compliance mode no one can delete a locked version or shorten its retention.' },
      { id: 'b', text: 'Enable S3 Object Lock in governance mode with a 6-year default retention.', why: 'Users with s3:BypassGovernanceRetention can delete objects in governance mode.' },
      { id: 'c', text: 'Enable versioning and MFA Delete.', why: 'The root user with MFA can still delete versions; this is not WORM.' },
      { id: 'd', text: 'Use a bucket policy that denies s3:DeleteObject.', why: 'Any administrator can edit or remove the bucket policy.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-iv-2',
    domain: 'secure',
    concepts: ['s3-versioning'],
    difficulty: 1,
    stem: 'Developers occasionally delete or overwrite important objects in an S3 bucket by mistake. The company needs to be able to recover any previous version of an object. What should a solutions architect do?',
    options: [
      { id: 'a', text: 'Enable S3 Versioning on the bucket.', why: 'Correct. Deletes become delete markers and overwrites keep the previous version, so both can be undone.' },
      { id: 'b', text: 'Enable S3 Transfer Acceleration.', why: 'It speeds up uploads; it doesn\'t keep old versions.' },
      { id: 'c', text: 'Move objects to S3 Standard-IA.', why: 'A storage class doesn\'t protect against deletes.' },
      { id: 'd', text: 'Enable server access logging.', why: 'Logs show who deleted what, but can\'t bring the data back.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-iv-3',
    domain: 'resilient',
    concepts: ['s3-replication'],
    difficulty: 2,
    stem: 'A company must keep a copy of every new object in an S3 bucket in another Region, and the business requires 99.99% of objects to be replicated within 15 minutes, with metrics to prove it. What should the solutions architect configure?',
    options: [
      { id: 'a', text: 'S3 Cross-Region Replication with S3 Replication Time Control (RTC).', why: 'Correct. RTC is backed by an SLA of 99.99% within 15 minutes and publishes replication metrics.' },
      { id: 'b', text: 'S3 Same-Region Replication.', why: 'SRR copies within the same Region; the requirement is another Region.' },
      { id: 'c', text: 'A nightly AWS DataSync task between the buckets.', why: 'A nightly job can leave objects unreplicated for up to a day.' },
      { id: 'd', text: 'S3 Cross-Region Replication without RTC.', why: 'Most objects replicate in seconds, but without RTC there is no 15-minute guarantee or replication metrics.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-iv-4',
    domain: 'secure',
    concepts: ['aws-backup', 'aws-organizations'],
    difficulty: 2,
    stem: 'After a ransomware attack at a competitor, a company wants to ensure that its AWS Backup recovery points cannot be deleted even if an attacker obtains administrator credentials in the production account. Which TWO actions help meet this requirement? (Select TWO.)',
    options: [
      { id: 'a', text: 'Enable AWS Backup Vault Lock in compliance mode on the vault.', why: 'Correct. Recovery points become immutable for their retention period, even for administrators.' },
      { id: 'b', text: 'Copy recovery points to a backup vault in a separate account.', why: 'Correct. The stolen credentials of the production account can\'t reach the other account\'s vault.' },
      { id: 'c', text: 'Increase the backup frequency to hourly.', why: 'More recovery points don\'t help if an administrator can delete all of them.' },
      { id: 'd', text: 'Encrypt the vault with an AWS managed key.', why: 'Encryption protects confidentiality, not deletion.' },
      { id: 'e', text: 'Move recovery points to cold storage after 7 days.', why: 'Cold storage lowers cost; it doesn\'t stop deletion.' },
    ],
    correct: ['a', 'b'],
  },
  {
    id: 'q-iv-5',
    domain: 'resilient',
    concepts: ['dynamodb-capacity', 'rds-backups'],
    difficulty: 2,
    stem: 'A faulty deployment wrote incorrect values to thousands of items in a DynamoDB table. The problem was discovered 30 hours later. The team wants to restore the table to its state just before the deployment. Which feature makes this possible?',
    options: [
      { id: 'a', text: 'DynamoDB point-in-time recovery (PITR).', why: 'Correct. PITR restores the table to any second in the last 35 days, into a new table.' },
      { id: 'b', text: 'DynamoDB global tables.', why: 'Global tables replicate the bad writes to every Region within seconds.' },
      { id: 'c', text: 'DynamoDB Streams.', why: 'Streams keep changes for 24 hours only, and replaying them is a custom project.' },
      { id: 'd', text: 'DAX.', why: 'DAX is a cache; it doesn\'t keep history.' },
    ],
    correct: ['a'],
  },

  // ----- The ever-growing archive (storage classes, lifecycle) -----
  {
    id: 'q-sc-1',
    domain: 'cost',
    concepts: ['s3-storage-classes'],
    difficulty: 2,
    stem: 'A hospital stores medical images that are rarely accessed after 30 days, but when a doctor requests one it must be available within milliseconds. Which storage class is the MOST cost-effective for images older than 30 days?',
    options: [
      { id: 'a', text: 'S3 Glacier Instant Retrieval.', why: 'Correct. Archive pricing with millisecond retrieval, for data accessed about once a quarter.' },
      { id: 'b', text: 'S3 Glacier Flexible Retrieval.', why: 'Objects must be restored first: minutes to hours, not milliseconds.' },
      { id: 'c', text: 'S3 Glacier Deep Archive.', why: 'Retrieval takes 12 to 48 hours.' },
      { id: 'd', text: 'S3 One Zone-IA.', why: 'Millisecond access, but data lives in one AZ: unacceptable for irreplaceable records, and dearer than Glacier IR.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-sc-2',
    domain: 'cost',
    concepts: ['s3-lifecycle'],
    difficulty: 2,
    stem: 'A team writes an S3 Lifecycle rule to move objects to S3 Standard-IA 7 days after creation. The rule is rejected. Why?',
    options: [
      { id: 'a', text: 'Objects must be stored at least 30 days in S3 Standard before transitioning to Standard-IA or One Zone-IA.', why: 'Correct. Lifecycle transitions to the IA classes require a minimum of 30 days.' },
      { id: 'b', text: 'Lifecycle rules can only transition objects to Glacier classes.', why: 'Rules can transition to IA, Intelligent-Tiering and Glacier classes.' },
      { id: 'c', text: 'Versioning must be enabled to use lifecycle rules.', why: 'Lifecycle rules work with or without versioning.' },
      { id: 'd', text: 'Standard-IA requires objects larger than 1 GB.', why: 'IA has a 128 KB minimum billable size, not 1 GB, and that doesn\'t block a rule.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-sc-3',
    domain: 'cost',
    concepts: ['s3-storage-classes'],
    difficulty: 1,
    stem: 'A company must keep audit logs for 10 years. They are almost never read, and when they are, a retrieval time of up to 48 hours is acceptable. Which storage class has the lowest cost?',
    options: [
      { id: 'a', text: 'S3 Glacier Deep Archive.', why: 'Correct. The lowest-cost class, with retrieval in 12 (standard) to 48 (bulk) hours.' },
      { id: 'b', text: 'S3 Glacier Instant Retrieval.', why: 'Millisecond retrieval the logs don\'t need, at about four times the price.' },
      { id: 'c', text: 'S3 Standard-IA.', why: 'Designed for infrequent but fast access; far more expensive per GB.' },
      { id: 'd', text: 'S3 Intelligent-Tiering.', why: 'Useful for unknown access patterns; here the pattern is known and Deep Archive is cheaper.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-sc-4',
    domain: 'cost',
    concepts: ['s3-storage-classes'],
    difficulty: 2,
    stem: 'A company stores thumbnails that can be regenerated from the original images at any time. Thumbnails are accessed infrequently but must load instantly. Which storage class is the MOST cost-effective?',
    options: [
      { id: 'a', text: 'S3 One Zone-IA.', why: 'Correct. Data that can be re-created tolerates a single AZ, and One Zone-IA is cheaper than Standard-IA with millisecond access.' },
      { id: 'b', text: 'S3 Standard.', why: 'Priced for frequent access; infrequent access makes it the expensive choice.' },
      { id: 'c', text: 'S3 Glacier Flexible Retrieval.', why: 'Thumbnails would need a restore before loading: not instant.' },
      { id: 'd', text: 'S3 Standard-IA.', why: 'It works, but it pays for multi-AZ resilience that re-creatable data doesn\'t need.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-sc-5',
    domain: 'cost',
    concepts: ['s3-storage-classes', 's3-lifecycle'],
    difficulty: 2,
    stem: 'A data lake bucket holds millions of objects whose access patterns are unpredictable: some old objects suddenly become popular again. The company wants to optimise storage costs automatically without retrieval fees or operational effort. Which solution meets these requirements?',
    options: [
      { id: 'a', text: 'Store the objects in S3 Intelligent-Tiering.', why: 'Correct. It moves objects between access tiers automatically based on use, with no retrieval fees (a small per-object monitoring fee).' },
      { id: 'b', text: 'A lifecycle rule that moves objects to Standard-IA after 30 days.', why: 'Objects that become popular again pay IA retrieval fees and stay in IA.' },
      { id: 'c', text: 'A lifecycle rule that moves objects to Glacier Deep Archive after 90 days.', why: 'Popular old objects would need restores taking hours.' },
      { id: 'd', text: 'A Lambda function that analyses access logs and moves objects.', why: 'It works in principle but is the operational effort the company wants to avoid.' },
    ],
    correct: ['a'],
  },

  // ----- Every click, twice (Kinesis, Firehose, Athena) -----
  {
    id: 'q-cs-1',
    domain: 'performant',
    concepts: ['kinesis-data-streams', 'messaging-fanout'],
    difficulty: 2,
    stem: 'An IoT platform ingests sensor readings. Three independent applications must each process every reading in real time, in order per device, and be able to reprocess the previous 7 days after a bug. Which service should receive the readings?',
    options: [
      { id: 'a', text: 'Amazon Kinesis Data Streams with a 7-day retention period.', why: 'Correct. Multiple consumers read the same records independently, ordered per partition key, with replay within the retention period.' },
      { id: 'b', text: 'Amazon SQS standard queue.', why: 'Each message goes to one consumer and is deleted once processed: no fan-out, no order, no replay.' },
      { id: 'c', text: 'Amazon Data Firehose.', why: 'Firehose delivers batches to destinations; it has no real-time consumers or replay.' },
      { id: 'd', text: 'Amazon SNS standard topic.', why: 'SNS fans out but doesn\'t keep messages for replay or guarantee order (standard topics).' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-cs-2',
    domain: 'performant',
    concepts: ['kinesis-firehose'],
    difficulty: 1,
    stem: 'A company wants to load streaming application logs into Amazon S3 in near real time and convert them to Apache Parquet, without writing or managing any consumer code. What should a solutions architect use?',
    options: [
      { id: 'a', text: 'Amazon Data Firehose with record format conversion to Parquet.', why: 'Correct. Firehose is fully managed delivery to S3 with built-in conversion to Parquet or ORC.' },
      { id: 'b', text: 'Kinesis Data Streams with a custom consumer on EC2.', why: 'It works, but the company would write and run the consumer.' },
      { id: 'c', text: 'Amazon SQS with a Lambda function that writes to S3.', why: 'That is custom code to build and maintain, plus conversion logic.' },
      { id: 'd', text: 'AWS DataSync.', why: 'DataSync copies files between storage systems; it doesn\'t ingest streams.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-cs-3',
    domain: 'cost',
    concepts: ['athena-glue'],
    difficulty: 2,
    stem: 'Analysts query JSON logs in S3 with Amazon Athena. Queries usually filter on a date and read a few columns, and the Athena bill is growing quickly. Which TWO changes reduce cost the most? (Select TWO.)',
    options: [
      { id: 'a', text: 'Convert the data to a columnar format such as Apache Parquet.', why: 'Correct. Athena then reads only the columns a query uses, and the data compresses well.' },
      { id: 'b', text: 'Partition the data by date.', why: 'Correct. Queries filtered on date scan only the matching partitions.' },
      { id: 'c', text: 'Move the data to S3 Standard-IA.', why: 'Athena bills per TB scanned; the storage class doesn\'t change how much is scanned (and IA adds retrieval fees).' },
      { id: 'd', text: 'Run the queries from an EC2 instance in the same Region.', why: 'The client\'s location doesn\'t change how much data Athena scans.' },
      { id: 'e', text: 'Increase the S3 request rate limit.', why: 'Request rates are not what Athena charges for.' },
    ],
    correct: ['a', 'b'],
  },
  {
    id: 'q-cs-4',
    domain: 'performant',
    concepts: ['kinesis-data-streams'],
    difficulty: 2,
    stem: 'Producers writing to a Kinesis data stream receive ProvisionedThroughputExceededException errors. The stream has 4 shards and receives 6 MB/s of data in 3,000 records per second. What should a solutions architect do?',
    options: [
      { id: 'a', text: 'Increase the number of shards to at least 6 (or switch to on-demand mode).', why: 'Correct. Each shard accepts 1 MB/s or 1,000 records/s; 6 MB/s needs at least 6 shards.' },
      { id: 'b', text: 'Enable enhanced fan-out.', why: 'Enhanced fan-out adds read throughput for consumers; the errors are on the write side.' },
      { id: 'c', text: 'Increase the retention period.', why: 'Retention controls how long records are kept, not ingest capacity.' },
      { id: 'd', text: 'Use a single partition key for all records.', why: 'That puts everything on one shard and makes throttling worse.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-cs-5',
    domain: 'resilient',
    concepts: ['messaging-fanout'],
    difficulty: 2,
    stem: 'When an order is placed, three services (billing, shipping and analytics) must each process it independently, and a slow or failing service must not affect the others. Which design meets these requirements?',
    options: [
      { id: 'a', text: 'Publish the order to an Amazon SNS topic with one SQS queue subscribed per service.', why: 'Correct. SNS fans out a copy to each queue; each service consumes at its own pace with its own retries and DLQ.' },
      { id: 'b', text: 'Send the order to one SQS queue that all three services poll.', why: 'Each message would be delivered to only one of the services.' },
      { id: 'c', text: 'Have the order service call the three services synchronously.', why: 'A slow or failing service would block or fail the order.' },
      { id: 'd', text: 'Write the order to S3 and have each service list the bucket.', why: 'Polling a bucket is slow, inefficient and has no delivery guarantees.' },
    ],
    correct: ['a'],
  },

  // ----- 80 TB by the end of the lease (Snow, DataSync, DMS) -----
  {
    id: 'q-mg-1',
    domain: 'performant',
    concepts: ['snow-family', 'data-migration'],
    difficulty: 2,
    stem: 'A research lab must move 150 TB of data to Amazon S3 within two weeks. Its internet connection is 200 Mbps and is also used by staff. What is the MOST efficient way to transfer the data?',
    options: [
      { id: 'a', text: 'Order AWS Snowball Edge Storage Optimized devices and ship the data.', why: 'Correct. At 200 Mbps the copy would take about 69 days even at full utilisation; shipping devices takes about a week.' },
      { id: 'b', text: 'Use S3 Transfer Acceleration.', why: 'It improves long-distance throughput but can\'t exceed the 200 Mbps line.' },
      { id: 'c', text: 'Order a 10 Gbps Direct Connect connection.', why: 'Provisioning takes weeks, missing the deadline before any data moves.' },
      { id: 'd', text: 'Use AWS DataSync over the internet.', why: 'DataSync is limited by the same 200 Mbps link.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-mg-2',
    domain: 'performant',
    concepts: ['datasync'],
    difficulty: 1,
    stem: 'A company wants to copy an on-premises NFS file share to Amazon EFS and then keep it synchronised every night, transferring only changed files, with the least operational overhead. Which service should it use?',
    options: [
      { id: 'a', text: 'AWS DataSync with a scheduled task.', why: 'Correct. DataSync copies NFS/SMB data to EFS, S3 or FSx and transfers only differences on each run.' },
      { id: 'b', text: 'AWS Database Migration Service.', why: 'DMS migrates databases, not file shares.' },
      { id: 'c', text: 'AWS Snowball Edge every night.', why: 'Shipping a device every night is neither practical nor low effort.' },
      { id: 'd', text: 'A cron job running rsync on an EC2 instance.', why: 'It can work but is the operational overhead DataSync removes.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-mg-3',
    domain: 'resilient',
    concepts: ['dms'],
    difficulty: 2,
    stem: 'A company is migrating a 2 TB on-premises Oracle database to Amazon Aurora PostgreSQL. The application must stay online during the migration with only a few minutes of downtime at cut-over. Which combination meets these requirements?',
    options: [
      { id: 'a', text: 'AWS Schema Conversion Tool for the schema, then AWS DMS with full load and ongoing replication (CDC).', why: 'Correct. SCT converts the Oracle schema and code; DMS copies the data and keeps it in sync until cut-over.' },
      { id: 'b', text: 'AWS DMS full load only.', why: 'Changes made during the copy are lost unless writes stop for the whole load.' },
      { id: 'c', text: 'Export with Oracle Data Pump, ship it on Snowball and import it.', why: 'The database would have to stop taking writes from export until import: days of downtime.' },
      { id: 'd', text: 'AWS DataSync of the database files.', why: 'Copying live database files doesn\'t produce a consistent database, and Oracle files can\'t be read by PostgreSQL.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-mg-4',
    domain: 'performant',
    concepts: ['datasync', 'block-file-storage'],
    difficulty: 2,
    stem: 'An on-premises application writes files to an NFS share. The company wants the files stored durably in Amazon S3, while the application keeps using NFS with low-latency access to recently used files. Which solution meets these requirements?',
    options: [
      { id: 'a', text: 'Deploy an Amazon S3 File Gateway (AWS Storage Gateway) on-premises.', why: 'Correct. It presents an NFS/SMB share backed by S3 with a local cache for recent data.' },
      { id: 'b', text: 'Mount Amazon EFS on-premises over the internet.', why: 'EFS needs VPN or Direct Connect, stores data in EFS rather than S3, and has no local cache.' },
      { id: 'c', text: 'Use Tape Gateway.', why: 'Tape Gateway presents a virtual tape library for backup software, not an NFS share.' },
      { id: 'd', text: 'Use AWS Snowball Edge.', why: 'Snowball is for one-off bulk transfers or edge computing, not an ongoing file share.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-mg-5',
    domain: 'secure',
    concepts: ['security-services'],
    difficulty: 1,
    stem: 'After migrating to AWS, a company needs to store database credentials securely and rotate them automatically every 30 days without changing application code beyond fetching the secret. Which service should be used?',
    options: [
      { id: 'a', text: 'AWS Secrets Manager.', why: 'Correct. Secrets Manager stores secrets and rotates them automatically, with built-in rotation for RDS and Aurora.' },
      { id: 'b', text: 'AWS Systems Manager Parameter Store standard parameters.', why: 'Parameter Store can hold secrets but has no built-in automatic rotation.' },
      { id: 'c', text: 'AWS KMS.', why: 'KMS manages encryption keys, not application secrets like passwords.' },
      { id: 'd', text: 'Amazon Macie.', why: 'Macie discovers sensitive data in S3; it doesn\'t store secrets.' },
    ],
    correct: ['a'],
  },
];
