import type { Question } from '../../engine/model';

// Stage 2 transfer questions: the same concepts as each incident and Spot the Difference round,
// in different stories. Every option explains itself.
export const STAGE2_QUESTIONS: Question[] = [
  // ----- The packet that never came back (NACLs, stateless) -----
  {
    id: 'q-inc1-1',
    domain: 'secure',
    concepts: ['nacls', 'sg-vs-nacl'],
    difficulty: 2,
    stem: 'A clinic runs a web server in a public subnet. A new network ACL on that subnet has inbound rule 100 allowing TCP 443 from 0.0.0.0/0 and outbound rule 100 allowing TCP 443 to 0.0.0.0/0. The security group allows inbound 443. Patients report that the site never loads. What should a solutions architect change?',
    options: [
      { id: 'a', text: 'Add an outbound NACL rule allowing TCP 1024-65535 to 0.0.0.0/0.', why: 'Correct. NACLs are stateless: the server\'s responses go to the browser\'s ephemeral port, and outbound 443 does not match them.' },
      { id: 'b', text: 'Add an outbound security group rule allowing TCP 1024-65535.', why: 'Security groups are stateful, so responses to allowed inbound traffic already leave. The NACL is what drops them.' },
      { id: 'c', text: 'Add an inbound NACL rule allowing TCP 1024-65535 from 0.0.0.0/0.', why: 'Wrong direction. Inbound ephemeral rules are for responses to connections the server starts, such as downloads.' },
      { id: 'd', text: 'Attach an Elastic IP address to the instance.', why: 'Requests already arrive (inbound 443 is accepted), so addressing is not the problem; the responses are dropped on the way out.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc1-2',
    domain: 'secure',
    concepts: ['vpc-flow-logs'],
    difficulty: 2,
    stem: 'A team needs to find out why TCP connections from a partner\'s IP range to an EC2 instance fail intermittently. They want to see which packets are accepted or rejected at the instance\'s network interface, with the least effort. What should they use?',
    options: [
      { id: 'a', text: 'VPC Flow Logs on the instance\'s ENI, published to CloudWatch Logs.', why: 'Correct. Flow log records include source, destination, ports and ACCEPT/REJECT for each flow at the ENI.' },
      { id: 'b', text: 'AWS CloudTrail data events for the EC2 instance and its network interface.', why: 'CloudTrail records API calls, not network packets reaching an instance.' },
      { id: 'c', text: 'VPC Traffic Mirroring to a packet-capture appliance.', why: 'It captures full packets but needs a target appliance and analysis tooling: far more effort than needed to see accept/reject decisions.' },
      { id: 'd', text: 'The CloudWatch NetworkIn and NetworkPacketsIn metrics for the instance.', why: 'NetworkIn counts bytes; it can\'t show which flows were rejected or why.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc1-3',
    domain: 'secure',
    concepts: ['sg-vs-nacl', 'nacls'],
    difficulty: 1,
    stem: 'A security team must block all traffic from a single abusive IP address range to every instance in a subnet, while leaving all other traffic unchanged. Which solution meets this requirement?',
    options: [
      { id: 'a', text: "Add a deny rule for the range to the subnet's network ACL, numbered below the existing allow rules.", why: 'Correct. NACLs support deny rules and evaluate in rule-number order, so a low-numbered deny wins.' },
      { id: 'b', text: 'Add a deny rule for the range to the security group of every instance in the subnet.', why: 'Security groups only support allow rules; there is no way to deny a range.' },
      { id: 'c', text: 'Add a deny rule for the range to the network ACL, numbered above the existing allow rule for 0.0.0.0/0.', why: 'The first matching rule wins: the broader allow matches first and the deny is never reached.' },
      { id: 'd', text: "Remove the internet gateway route from the subnet's route table until the abuse stops.", why: 'That cuts the subnet off from the entire internet, not just one range.' },
    ],
    correct: ['a'],
  },

  // ----- Patch Tuesday, again (blackhole routes, NAT per AZ) -----
  {
    id: 'q-inc2-1',
    domain: 'resilient',
    concepts: ['route-blackholes', 'nat-gateway'],
    difficulty: 2,
    stem: 'A media company\'s private subnets in us-west-2a can no longer reach a third-party API, while identical subnets in us-west-2b can. The route table for us-west-2a shows the 0.0.0.0/0 route with status "Blackhole". What is the MOST likely cause?',
    options: [
      { id: 'a', text: 'The NAT gateway the route points to was deleted.', why: 'Correct. Routes to deleted targets stay in the table as blackholes and drop matching traffic.' },
      { id: 'b', text: 'The internet gateway was detached from the VPC.', why: 'That would break both AZs and the public subnets too, not just one private route table.' },
      { id: 'c', text: 'The third-party API blocked the company\'s IP addresses.', why: 'A blocked IP would not change the route status to Blackhole, and both AZs would likely be affected.' },
      { id: 'd', text: 'The security group on the instances has no outbound rules.', why: 'Security groups don\'t change route status, and the instances in us-west-2b would share the same groups.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc2-2',
    domain: 'resilient',
    concepts: ['nat-gateway'],
    difficulty: 2,
    stem: 'An application in private subnets across three Availability Zones must keep outbound internet access if any single AZ fails. Which design meets this requirement?',
    options: [
      { id: 'a', text: 'A NAT gateway in a public subnet in each AZ, with each private route table using the one in its own AZ.', why: 'Correct. NAT gateways are zonal; one per AZ means an AZ failure only affects that AZ\'s own subnets.' },
      { id: 'b', text: 'One NAT gateway in the first AZ for all private subnets, since NAT gateways are redundant within their AZ.', why: 'If that AZ fails, every private subnet loses outbound access. It also adds cross-AZ data charges.' },
      { id: 'c', text: 'Two NAT gateways in the same public subnet, with private route tables split between them.', why: 'Both sit in one AZ and fail together with it.' },
      { id: 'd', text: 'A route to the internet gateway in the private route tables, which AWS runs across all AZs.', why: 'Instances without public IPs can\'t use an internet gateway, and doing so would make the subnets public.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc2-3',
    domain: 'secure',
    concepts: ['cloudtrail'],
    difficulty: 1,
    stem: 'An operations manager wants to know which IAM user deleted a production NAT gateway yesterday afternoon. No additional logging was configured. Where can the answer be found?',
    options: [
      { id: 'a', text: 'CloudTrail Event history, filtered on the DeleteNatGateway event name.', why: 'Correct. Management events are recorded by default and kept in Event history for 90 days.' },
      { id: 'b', text: 'VPC Flow Logs for the public subnet.', why: 'Flow logs record network traffic, not who called which API.' },
      { id: 'c', text: 'The CloudWatch metrics for the NAT gateway.', why: 'Metrics stop when the resource disappears, but they never record who deleted it.' },
      { id: 'd', text: 'AWS Config, but only if a delivery channel was set up beforehand.', why: 'Config records configuration changes only when it was already enabled; the scenario says nothing extra was configured. CloudTrail needs no setup for this.' },
    ],
    correct: ['a'],
  },

  // ----- 0/4 healthy (health checks, fail-open, churn) -----
  {
    id: 'q-inc3-1',
    domain: 'resilient',
    concepts: ['alb-health-checks', 'asg-health-checks'],
    difficulty: 2,
    stem: 'After a release, an Auto Scaling group behind an Application Load Balancer keeps terminating and replacing instances every few minutes. The application works when tested directly on an instance. The target group shows 0 healthy targets. The group uses ELB health checks. What is the MOST likely cause?',
    options: [
      { id: 'a', text: "The target group's health check path no longer matches a URL the release serves.", why: 'Correct. Every check fails, so Auto Scaling (using ELB health checks) replaces every instance after the grace period, over and over.' },
      { id: 'b', text: "The Auto Scaling group's maximum capacity is too low for the new release.", why: 'Max capacity limits growth; it doesn\'t cause healthy-looking instances to be terminated.' },
      { id: 'c', text: 'Cross-zone load balancing is disabled on the load balancer.', why: 'That affects traffic distribution, not whether targets pass health checks.' },
      { id: 'd', text: 'The new release needs more memory than the instance type provides.', why: 'An undersized instance might fail checks under load, but the app works when tested and the failures started with the release.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc3-2',
    domain: 'resilient',
    concepts: ['alb-error-codes'],
    difficulty: 2,
    stem: 'Users of a ticketing site intermittently receive HTTP 503 errors generated by the Application Load Balancer itself (no target status code in the access logs). Which condition produces this error?',
    options: [
      { id: 'a', text: 'The target group has no registered targets at that moment.', why: 'Correct. With nothing registered (for example while instances are being replaced), the ALB answers 503.' },
      { id: 'b', text: 'A target took longer than the idle timeout to respond.', why: 'That produces 504 Gateway Timeout.' },
      { id: 'c', text: 'A target closed the connection or sent a malformed response.', why: 'That produces 502 Bad Gateway.' },
      { id: 'd', text: 'The application returned an error for a bad request.', why: 'The application\'s own errors show up with a target status code, not as an ELB-generated 503.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc3-3',
    domain: 'resilient',
    concepts: ['alb-health-checks'],
    difficulty: 3,
    stem: 'The health check path on an Application Load Balancer target group was misconfigured, so all four registered targets show as unhealthy. The Auto Scaling group uses EC2 health checks. Customers report the site still works normally. Why?',
    options: [
      { id: 'a', text: 'When every target is unhealthy, the ALB fails open and sends requests to all targets.', why: 'Correct. Fail-open keeps serving; with EC2 health checks the group also leaves the instances alone, which hides the misconfiguration until something really breaks.' },
      { id: 'b', text: 'The ALB caches recent responses and serves them while targets are unhealthy.', why: 'An ALB does not cache responses.' },
      { id: 'c', text: 'Route 53 health checks send users straight to the instances when the ALB fails.', why: 'Nothing redirects users around the load balancer; the instances are in private subnets.' },
      { id: 'd', text: 'Unhealthy targets keep receiving existing connections for up to an hour before they are drained.', why: 'There is no such delay; targets are marked unhealthy after interval × unhealthy threshold.' },
    ],
    correct: ['a'],
  },

  // ----- The wrong door (SG referencing) -----
  {
    id: 'q-inc4-1',
    domain: 'secure',
    concepts: ['sg-chaining'],
    difficulty: 2,
    stem: 'A three-tier application has security groups web-sg (ALB), app-sg (EC2 Auto Scaling group) and db-sg (Aurora). Only the application tier may connect to the database, including instances launched later by scaling. Which db-sg inbound rule meets this requirement?',
    options: [
      { id: 'a', text: 'Allow TCP 3306 from source app-sg.', why: 'Correct. A security group reference matches any ENI carrying app-sg, including future instances, and nothing else.' },
      { id: 'b', text: 'Allow TCP 3306 from the VPC CIDR.', why: 'That lets every resource in the VPC (including the load balancer) reach the database.' },
      { id: 'c', text: 'Allow TCP 3306 from source web-sg.', why: 'web-sg is on the load balancer, which never talks to the database; the app instances would be blocked.' },
      { id: 'd', text: 'Allow TCP 3306 from the private IP of each app instance.', why: 'Instance IPs change as the group scales, so the rule goes stale immediately.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc4-2',
    domain: 'secure',
    concepts: ['security-groups', 'vpc-flow-logs'],
    difficulty: 2,
    stem: 'An application logs "connection timed out" when connecting to its database, rather than "connection refused". Which explanation fits a timeout best?',
    options: [
      { id: 'a', text: 'A security group or network ACL is silently dropping the packets.', why: 'Correct. Firewalls in a VPC drop without replying, so the client waits and times out. Flow logs will show REJECT.' },
      { id: 'b', text: 'The database process has stopped and is no longer listening on its port.', why: 'A reachable host with nothing listening answers with a TCP reset: "connection refused".' },
      { id: 'c', text: 'The application is sending the wrong password for the database user.', why: 'Authentication errors arrive after the connection is made, with an explicit access-denied message.' },
      { id: 'd', text: 'The database has reached its max_connections limit and is rejecting new sessions.', why: 'The server answers with a "too many connections" error; it does not time out.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc4-3',
    domain: 'secure',
    concepts: ['sg-chaining', 'security-groups'],
    difficulty: 1,
    stem: 'A Lambda function in a VPC must connect to an RDS for PostgreSQL instance. Both are in the same VPC. What is the MOST secure way to allow this?',
    options: [
      { id: 'a', text: "Give the function its own security group and allow TCP 5432 from that group in the database's group.", why: 'Correct. Security group referencing grants exactly the function\'s ENIs, whatever IPs they get.' },
      { id: 'b', text: 'Allow TCP 5432 from 0.0.0.0/0 in the database security group, since the database sits in a private subnet.', why: 'Being private is not a firewall: anything in the VPC or connected networks could reach the database.' },
      { id: 'c', text: 'Make the database publicly accessible and connect to its public endpoint over TLS from the function.', why: 'That exposes the database to the internet for no benefit.' },
      { id: 'd', text: "Add network ACL rules that allow all traffic between the function's subnets and the database subnets.", why: 'NACLs work on CIDRs and are subnet-wide; they can\'t single out the function.' },
    ],
    correct: ['a'],
  },

  // ----- AccessDenied at 2 a.m. (identity policies, least privilege) -----
  {
    id: 'q-inc5-1',
    domain: 'secure',
    concepts: ['iam-policy-evaluation', 'iam-roles'],
    difficulty: 2,
    stem: 'A Lambda function that processes payroll files fails with: "User: arn:aws:sts::123456789012:assumed-role/payroll-fn-role/payroll-fn is not authorized to perform: sqs:SendMessage on resource: arn:aws:sqs:eu-west-1:123456789012:payslips because no identity-based policy allows the sqs:SendMessage action". The queue has no queue policy. What is the LEAST-privilege fix?',
    options: [
      { id: 'a', text: 'Add an Allow for sqs:SendMessage on the payslips queue ARN to payroll-fn-role.', why: 'Correct. The message names the role, the action and the resource: grant exactly that.' },
      { id: 'b', text: 'Attach the AmazonSQSFullAccess managed policy to payroll-fn-role.', why: 'It works but grants every SQS action on every queue: not least privilege.' },
      { id: 'c', text: 'Add a queue policy allowing Principal "*" to send messages.', why: 'That lets anyone in the world send messages to the queue.' },
      { id: 'd', text: 'Create an IAM user with access keys and store them in the function\'s environment variables.', why: 'Long-term keys in environment variables are a security risk; execution roles exist to avoid them.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc5-2',
    domain: 'secure',
    concepts: ['iam-policy-evaluation'],
    difficulty: 2,
    stem: 'A role has two identity policies. Policy A allows s3:* on arn:aws:s3:::reports/*. Policy B denies s3:DeleteObject on arn:aws:s3:::reports/*. What happens when the role calls s3:DeleteObject on reports/q1.pdf?',
    options: [
      { id: 'a', text: 'Denied, because an explicit deny overrides any allow.', why: 'Correct. Explicit deny is evaluated first and always wins.' },
      { id: 'b', text: 'Allowed, because s3:* is broader than s3:DeleteObject.', why: 'Breadth doesn\'t matter: any explicit deny that matches wins.' },
      { id: 'c', text: 'Allowed, because policy A was attached first.', why: 'Policy order and attachment order play no part in evaluation.' },
      { id: 'd', text: 'Denied, because S3 requires a bucket policy for deletes.', why: 'Same-account access can be granted by identity policies alone; the deny is what blocks it.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc5-3',
    domain: 'secure',
    concepts: ['cloudtrail'],
    difficulty: 2,
    stem: 'Security wants a record of every GetItem and PutItem call made against a DynamoDB table holding customer addresses, including who made it. What must be configured?',
    options: [
      { id: 'a', text: 'A CloudTrail trail (or event data store) with data events enabled for the table.', why: 'Correct. Item-level calls are data events, which are not logged by default.' },
      { id: 'b', text: 'Nothing extra: CloudTrail Event history already records these calls for 90 days.', why: 'Event history only contains management events such as CreateTable or UpdateTable.' },
      { id: 'c', text: 'DynamoDB Streams on the table, with a Lambda function that writes each record to S3.', why: 'Streams capture item changes (not reads such as GetItem), and they do not record who made the call.' },
      { id: 'd', text: 'VPC Flow Logs on the subnets that reach DynamoDB through the gateway endpoint.', why: 'Flow logs show packets, not API calls or identities.' },
    ],
    correct: ['a'],
  },

  // ----- The key that wouldn't turn (KMS key policies) -----
  {
    id: 'q-inc6-1',
    domain: 'secure',
    concepts: ['kms-key-policies'],
    difficulty: 3,
    stem: 'An EC2 role has an IAM policy allowing s3:GetObject on a bucket and kms:Decrypt on all keys. The bucket uses SSE-KMS with a customer managed key whose key policy only allows a key-admins role. Listing objects works, but GetObject returns AccessDenied. What should be changed?',
    options: [
      { id: 'a', text: 'Allow the EC2 role kms:Decrypt in the key policy, or add the statement that enables IAM policies.', why: 'Correct. For KMS the key policy is required; without it, the role\'s IAM permission for kms:Decrypt is ignored.' },
      { id: 'b', text: "Add kms:* on the key's ARN to the EC2 role's IAM policy so the role can use every operation on the key.", why: 'The role already has kms:Decrypt in IAM. IAM policies only count if the key policy delegates to the account.' },
      { id: 'c', text: 'Add the EC2 role as a principal with s3:GetObject in the bucket policy so the bucket trusts it directly.', why: 'S3 already allows the call (listing works and the S3 permission is there); the failure is the KMS call S3 makes for the role.' },
      { id: 'd', text: 'Enable S3 Bucket Keys on the bucket so S3 uses a bucket-level data key instead of calling KMS.', why: 'Bucket Keys reduce KMS request volume and cost; they don\'t change who may use the key.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc6-2',
    domain: 'secure',
    concepts: ['kms-key-policies', 'encryption-at-rest'],
    difficulty: 2,
    stem: 'A healthcare company must control who can decrypt patient documents in S3, rotate the key on its own schedule, and see every use of the key in an audit log. Which encryption option meets these requirements?',
    options: [
      { id: 'a', text: 'SSE-KMS with a customer managed key.', why: 'Correct. You own the key policy and the rotation settings, and every use appears in CloudTrail.' },
      { id: 'b', text: 'SSE-S3.', why: 'S3 manages the keys entirely; there is no key policy to control or per-use audit trail.' },
      { id: 'c', text: 'SSE-KMS with the AWS managed key aws/s3.', why: 'Use is logged, but you can\'t edit its key policy or change its rotation.' },
      { id: 'd', text: 'Client-side encryption with keys stored on the application servers.', why: 'It moves all key management, rotation and auditing onto the company, with keys sitting on servers.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc6-3',
    domain: 'secure',
    concepts: ['kms-key-policies', 'resource-vs-identity-policies'],
    difficulty: 3,
    stem: 'Account B needs to read SSE-KMS-encrypted objects from a bucket in account A. The bucket policy already grants account B s3:GetObject, and account B\'s role has an IAM policy allowing s3:GetObject and kms:Decrypt. Reads still fail. What is missing?',
    options: [
      { id: 'a', text: 'The key policy in account A must allow account B (or its role) to use kms:Decrypt.', why: 'Correct. Cross-account key use needs the key policy to allow the other account, plus the IAM permission in that account (which exists).' },
      { id: 'b', text: 'Account B must create its own KMS key with the same key material and re-encrypt its copy.', why: 'Customer managed keys can\'t be duplicated that way; the objects are encrypted under account A\'s key.' },
      { id: 'c', text: 'S3 Object Ownership must be set to Bucket owner enforced so account A owns every object.', why: 'Object ownership affects ACLs, not KMS permissions.' },
      { id: 'd', text: "Account B's role needs s3:* on the bucket instead of only s3:GetObject to read encrypted objects.", why: 'The S3 side is already allowed on both sides; broader S3 rights don\'t fix the key.' },
    ],
    correct: ['a'],
  },

  // ----- Locked out by your own policy (conditions, explicit deny) -----
  {
    id: 'q-inc7-1',
    domain: 'secure',
    concepts: ['iam-condition-keys', 'vpc-endpoint-policies'],
    difficulty: 2,
    stem: 'A company wants an S3 bucket to be accessible only from applications in its VPC, which reach S3 through a gateway endpoint. Which bucket policy statement meets this requirement?',
    options: [
      { id: 'a', text: 'A Deny for s3:* with the condition StringNotEquals aws:SourceVpce set to the endpoint ID.', why: 'Correct. Requests that don\'t come through the endpoint carry no matching aws:SourceVpce, so the deny applies to them.' },
      { id: 'b', text: 'An Allow for s3:* with the condition IpAddress aws:SourceIp set to the VPC CIDR.', why: 'Requests through a VPC endpoint don\'t carry aws:SourceIp, and an Allow doesn\'t stop other principals who are allowed elsewhere.' },
      { id: 'c', text: 'A Deny for s3:* with the condition Bool aws:SecureTransport false.', why: 'That enforces HTTPS, not the network path.' },
      { id: 'd', text: 'An endpoint policy that allows only this bucket.', why: 'That limits what the VPC can reach; it doesn\'t stop access to the bucket from elsewhere.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc7-2',
    domain: 'secure',
    concepts: ['iam-condition-keys', 'iam-policy-evaluation'],
    difficulty: 3,
    stem: 'A bucket policy denies all S3 actions unless aws:SourceVpce matches the company\'s endpoint. Administrators using the S3 console from the office are now denied. The VPC restriction must stay in place for everyone else. What should a solutions architect do?',
    options: [
      { id: 'a', text: "Add a condition to the same Deny statement: ArnNotLike aws:PrincipalArn set to the admins' role ARN.", why: 'Correct. Conditions are ANDed: the deny now applies only to requests that are both outside the VPC endpoint and not from the admin role.' },
      { id: 'b', text: "Add an Allow statement for the administrators' role to the bucket policy, above the existing Deny.", why: 'An explicit deny always beats an allow, so the admins stay locked out.' },
      { id: 'c', text: "Attach the AdministratorAccess managed policy to the administrators' role so it can use every S3 action.", why: 'Identity policies can\'t override an explicit deny in a resource policy.' },
      { id: 'd', text: 'Remove the Deny statement and rely on IAM policies to keep everyone else inside the VPC.', why: 'That drops the VPC restriction for everyone, which the requirement forbids.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc7-3',
    domain: 'secure',
    concepts: ['iam-condition-keys'],
    difficulty: 2,
    stem: 'A company wants to share an S3 bucket of internal templates with every account in its AWS Organization, including accounts created in the future, without listing account IDs. Which bucket policy approach meets this requirement?',
    options: [
      { id: 'a', text: 'Allow Principal "*" with the condition StringEquals aws:PrincipalOrgID set to the organization ID.', why: 'Correct. Only principals in the organization match, and new accounts are included automatically.' },
      { id: 'b', text: 'Allow Principal "*" with no condition, since only employees know the bucket name.', why: 'That makes the bucket public to every AWS customer and the internet.' },
      { id: 'c', text: 'List every account root ARN in the Principal element and update it as accounts are added.', why: 'It works but needs constant maintenance, which the requirement rules out.' },
      { id: 'd', text: 'Use an SCP that allows s3:GetObject on the bucket.', why: 'SCPs never grant access; they only limit it.' },
    ],
    correct: ['a'],
  },

  // ----- The zombie fleet (ASG health check type) -----
  {
    id: 'q-inc8-1',
    domain: 'resilient',
    concepts: ['asg-health-checks'],
    difficulty: 2,
    stem: 'Instances in an Auto Scaling group behind an Application Load Balancer sometimes hang: the OS stays up, but the web process stops responding. The load balancer marks them unhealthy, but they are never replaced. What should a solutions architect do?',
    options: [
      { id: 'a', text: 'Change the Auto Scaling group health check type to ELB and set a suitable grace period.', why: 'Correct. Then the group replaces instances that fail the load balancer\'s health checks, not only those that fail EC2 status checks.' },
      { id: 'b', text: 'Enable detailed monitoring on the instances so that hung instances are detected within one minute.', why: 'One-minute metrics don\'t change what Auto Scaling treats as unhealthy.' },
      { id: 'c', text: 'Increase the desired capacity so there are spare instances when some of them hang.', why: 'More instances hide the problem; the hung ones still sit there doing nothing.' },
      { id: 'd', text: 'Create a CloudWatch alarm on StatusCheckFailed that reboots the instance.', why: 'Status checks pass because the OS is healthy, so the alarm never fires.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc8-2',
    domain: 'resilient',
    concepts: ['asg-health-checks'],
    difficulty: 3,
    stem: 'After switching an Auto Scaling group to ELB health checks, newly launched instances are terminated about a minute after launch, before the application (which takes 4 minutes to start) is ready. What is the cause?',
    options: [
      { id: 'a', text: 'The health check grace period is shorter than the application startup time.', why: 'Correct. During startup the instance fails health checks; once the grace period ends, the group terminates it.' },
      { id: 'b', text: 'The instance warmup for the scaling policies is longer than the application startup time.', why: 'Warmup affects scaling metrics, not health-based replacement.' },
      { id: 'c', text: 'The load balancer has cross-zone load balancing enabled, so new targets get traffic too early.', why: 'Cross-zone balancing has no effect on when instances are considered unhealthy.' },
      { id: 'd', text: 'The Auto Scaling group\'s maximum capacity has been reached.', why: 'Reaching max stops new launches; it doesn\'t terminate instances.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-inc8-3',
    domain: 'resilient',
    concepts: ['cloudwatch-metrics'],
    difficulty: 1,
    stem: 'An operations team wants to be alerted when the memory usage of EC2 instances exceeds 85%. What is required?',
    options: [
      { id: 'a', text: 'Install the CloudWatch agent so the instances publish memory metrics, then create an alarm.', why: 'Correct. Memory is inside the guest OS, so EC2 doesn\'t report it by default.' },
      { id: 'b', text: 'Enable detailed monitoring on the instances, then create an alarm on memory usage.', why: 'Detailed monitoring makes default metrics more frequent; it doesn\'t add memory.' },
      { id: 'c', text: 'Create a CloudWatch alarm on the default EC2 MemoryUtilization metric at a threshold of 85%.', why: 'There is no default EC2 memory metric.' },
      { id: 'd', text: 'Turn on VPC Flow Logs and alarm when an instance stops sending traffic.', why: 'Flow logs record network traffic, not memory.' },
    ],
    correct: ['a'],
  },

  // ----- Spot the Difference rounds -----
  {
    id: 'q-diff1-1',
    domain: 'resilient',
    concepts: ['rds-multi-az', 'rds-read-replicas'],
    difficulty: 2,
    stem: 'An e-commerce database on Amazon RDS for MySQL must fail over automatically within two minutes with no data loss if an Availability Zone fails. Reporting queries are also slowing it down. Which TWO actions meet these requirements? (Choose TWO.)',
    options: [
      { id: 'a', text: 'Enable Multi-AZ on the DB instance.', why: 'Correct. A synchronous standby with automatic failover gives RPO 0 and a failover in about 60-120 seconds.' },
      { id: 'b', text: 'Create a read replica and point the reporting queries at it.', why: 'Correct. Replicas offload reads; they are the right tool for the reporting load.' },
      { id: 'c', text: 'Create a read replica in another AZ and rely on it for failover.', why: 'Replication is asynchronous and promotion is manual, so neither the automatic failover nor the zero data loss requirement is met.' },
      { id: 'd', text: 'Increase the backup retention period to 35 days.', why: 'Longer retention helps restores, which take far longer than two minutes and lose recent writes.' },
    ],
    correct: ['a', 'b'],
  },
  {
    id: 'q-diff1-2',
    domain: 'resilient',
    concepts: ['rds-multi-az'],
    difficulty: 1,
    stem: 'What does an application need to change after an RDS Multi-AZ failover?',
    options: [
      { id: 'a', text: "Nothing: the endpoint's DNS name now points at the new primary, so reconnecting is enough.", why: 'Correct. RDS flips the DNS record; apps should retry connections.' },
      { id: 'b', text: "Update the connection string to the standby's endpoint, which is now the primary.", why: 'The standby has no separate endpoint; the same DNS name follows the primary.' },
      { id: 'c', text: 'Restore the latest automated snapshot to a new instance and point the application at it.', why: 'Failover uses the synchronous standby; no restore is needed.' },
      { id: 'd', text: 'Promote the standby manually in the console before the application can write again.', why: 'Multi-AZ failover is automatic.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-diff2-1',
    domain: 'secure',
    concepts: ['sg-vs-nacl'],
    difficulty: 2,
    stem: 'Which statements about security groups and network ACLs are correct? (Choose TWO.)',
    options: [
      { id: 'a', text: 'Security groups are stateful; return traffic is allowed automatically.', why: 'Correct. Connection tracking lets responses through regardless of the rules in the other direction.' },
      { id: 'b', text: 'Network ACLs are stateless; return traffic must be allowed by explicit rules.', why: 'Correct. That\'s why NACLs need ephemeral port rules.' },
      { id: 'c', text: 'Security groups evaluate rules in number order, and the first match wins.', why: 'Security group rules have no order; all are evaluated together.' },
      { id: 'd', text: 'Network ACLs can reference security groups as the source or destination of a rule.', why: 'NACL rules only use CIDR blocks.' },
    ],
    correct: ['a', 'b'],
  },
  {
    id: 'q-diff2-2',
    domain: 'secure',
    concepts: ['security-groups'],
    difficulty: 2,
    stem: 'A security group attached to a web server has inbound TCP 443 from 0.0.0.0/0 and NO outbound rules. The subnet uses the default network ACL. What happens?',
    options: [
      { id: 'a', text: "HTTPS requests are served normally, but the server can't open new outbound connections.", why: 'Correct. Responses ride the tracked inbound connection; new outbound connections need an outbound rule.' },
      { id: 'b', text: 'HTTPS requests time out because responses are blocked on the way out.', why: 'That would be true for a NACL, not for a stateful security group.' },
      { id: 'c', text: 'Nothing works until an outbound rule for the ephemeral ports 1024-65535 is added.', why: 'Security groups never need ephemeral-port rules for responses.' },
      { id: 'd', text: 'AWS rejects a security group that has no outbound rules when you save it.', why: 'Empty outbound rules are valid; they simply allow no new outbound connections.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-diff3-1',
    domain: 'cost',
    concepts: ['vpc-gateway-endpoints', 'nat-data-processing'],
    difficulty: 2,
    stem: 'A data pipeline in private subnets across three AZs moves 40 TB per month to S3 through NAT gateways. Which change reduces cost the MOST with the least effort?',
    options: [
      { id: 'a', text: 'Create an S3 gateway endpoint and associate it with all three private route tables.', why: 'Correct. Gateway endpoints are free and remove NAT data processing charges for S3 traffic from every associated subnet.' },
      { id: 'b', text: 'Create an S3 gateway endpoint and associate it with one private route table.', why: 'Only that route table\'s subnets benefit; the other two AZs keep paying NAT processing.' },
      { id: 'c', text: 'Create an S3 interface endpoint in each AZ.', why: 'It works but costs per hour and per GB, unlike the free gateway endpoint.' },
      { id: 'd', text: 'Replace the NAT gateways with larger instances running NAT software.', why: 'More to manage, and still no saving on the data path itself compared with a free endpoint.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-diff3-2',
    domain: 'secure',
    concepts: ['vpc-endpoint-policies'],
    difficulty: 3,
    stem: 'A company wants to prevent instances in its VPC from uploading data to S3 buckets owned by other AWS accounts, while allowing access to its own buckets. Instances reach S3 through a gateway endpoint. What should be configured?',
    options: [
      { id: 'a', text: "An endpoint policy that allows S3 actions only on the company's buckets (aws:ResourceAccount).", why: 'Correct. Endpoint policies filter every request through the endpoint, whatever the instance\'s IAM role allows.' },
      { id: 'b', text: 'A bucket policy on each company bucket that denies requests unless aws:SourceVpce is the endpoint.', why: 'That protects the company\'s buckets from outside access; it does nothing about uploads to other people\'s buckets.' },
      { id: 'c', text: 'A security group rule that allows outbound HTTPS only to the S3 managed prefix list.', why: 'The prefix list covers all of S3, including other accounts\' buckets.' },
      { id: 'd', text: 'Remove the NAT gateway so instances can reach S3 only through the gateway endpoint.', why: 'S3 traffic already uses the endpoint, and removing the NAT doesn\'t restrict which buckets it reaches.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-diff4-1',
    domain: 'performant',
    concepts: ['asg-scaling'],
    difficulty: 2,
    stem: 'A payroll portal is idle most of the month, but every 25th at 08:00 thousands of employees log in within minutes. Target tracking scaling reacts too late and users see errors for the first 10 minutes. Which solution fixes this with the LEAST operational overhead?',
    options: [
      { id: 'a', text: 'Add a scheduled scaling action that raises the desired capacity at 07:45 on the 25th.', why: 'Correct. Capacity is booted and warm before the known spike arrives; target tracking still handles the rest.' },
      { id: 'b', text: 'Lower the target tracking CPU target to 20% so the group scales out sooner.', why: 'More headroom all month long costs money and still lags a sudden 10× jump.' },
      { id: 'c', text: 'Set the minimum capacity to the peak size permanently so capacity is always there.', why: 'It works but pays for peak capacity 30 days a month.' },
      { id: 'd', text: 'Shorten the instance warmup to 0 seconds so new instances count immediately.', why: 'Instances still need time to boot; a zero warmup only makes scaling decisions on bad metrics.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-diff4-2',
    domain: 'performant',
    concepts: ['asg-scaling'],
    difficulty: 2,
    stem: 'A news site sees unpredictable traffic spikes when stories go viral, and also a daily cycle that repeats every weekday. Which combination scales the Auto Scaling group MOST effectively?',
    options: [
      { id: 'a', text: 'Predictive scaling for the daily pattern plus target tracking for surprise spikes.', why: 'Correct. Predictive scaling forecasts the recurring cycle and launches ahead of it; target tracking reacts to the surprises.' },
      { id: 'b', text: 'Scheduled scaling actions for the daily peak, with no other policy.', why: 'Schedules can\'t anticipate viral stories.' },
      { id: 'c', text: 'Simple scaling on CPU with a 30-minute cooldown between actions.', why: 'Long cooldowns make it slower to react to spikes.' },
      { id: 'd', text: 'A fixed fleet sized for the largest spike ever seen, plus 20% headroom.', why: 'Expensive, and the next spike may be bigger.' },
    ],
    correct: ['a'],
  },
];
