import type { Question } from '../../engine/model';

// Stage 4 questions: the refactor missions' concepts in different stories, then bank-balancing
// questions so a 65-question practice exam can be drawn with the SAA-C03 domain weights.
// Every option explains itself. Correct answers are spread across positions on purpose.
export const STAGE4_QUESTIONS: Question[] = [
  // ----- The render farm (Spot) -----
  {
    id: 'q-rf-spot-1',
    domain: 'cost',
    concepts: ['ec2-spot'],
    difficulty: 1,
    stem: 'A media company transcodes video files from an Amazon SQS queue. Each job takes about 5 minutes, writes its output to Amazon S3, and can be safely retried if it is interrupted. The workload runs around the clock. Which purchasing option is the MOST cost-effective for the worker instances?',
    options: [
      { id: 'a', text: 'Dedicated Hosts, so the transcoding fleet has the servers to itself', why: 'Dedicated Hosts are for licensing or compliance needs that require a physical server. They are the most expensive way to run this.' },
      { id: 'b', text: 'On-Demand Instances in an Auto Scaling group that scales on queue depth', why: 'On-Demand works, but the jobs are short, retryable and queue-driven: exactly the profile Spot discounts by up to 90%.' },
      { id: 'c', text: 'Spot Instances in an Auto Scaling group with several instance types', why: 'Correct. The work is stateless and retryable: an interrupted job just goes back to the queue. Several instance types give the group more Spot pools to draw from.' },
      { id: 'd', text: 'A Compute Savings Plan sized for the peak fleet', why: 'Committing to the peak means paying for idle commitment off-peak, and even the committed rate is well above typical Spot prices for interruptible work.' },
    ],
    correct: ['c'],
  },
  {
    id: 'q-rf-spot-2',
    domain: 'cost',
    concepts: ['ec2-spot', 'asg-scaling'],
    difficulty: 2,
    stem: 'An Auto Scaling group runs a fault-tolerant batch fleet entirely on Spot Instances of a single instance type with the lowest-price allocation strategy. During busy periods most of the fleet is interrupted at the same time. Which change reduces interruptions while keeping costs low?',
    options: [
      { id: 'a', text: 'Add several similar instance types and use the price-capacity-optimized strategy.', why: 'Correct. More instance types mean more Spot capacity pools, and price-capacity-optimized launches into the pools least likely to be interrupted while still weighing price.' },
      { id: 'b', text: 'Keep one instance type and raise the maximum Spot price to the On-Demand price.', why: "Spot interruptions today are driven by EC2 needing the capacity back, not by your maximum price. Bidding higher doesn't keep the instances." },
      { id: 'c', text: 'Switch the allocation strategy to lowest-price across more Availability Zones only.', why: "Lowest-price concentrates the fleet in the cheapest pools, which are often the first to be reclaimed. That's the cause, not the fix." },
      { id: 'd', text: 'Move the whole fleet to On-Demand Instances in the same instance type.', why: "That ends interruptions but gives up the Spot discount entirely. The workload is fault-tolerant, so it doesn't need to." },
    ],
    correct: ['a'],
  },
  {
    id: 'q-rf-spot-3',
    domain: 'resilient',
    concepts: ['ec2-spot'],
    difficulty: 2,
    stem: 'A scientific simulation runs for several hours on Spot Instances. When an instance is interrupted, the run starts again from the beginning and the deadline is missed. How should a solutions architect make the workload tolerant of interruptions?',
    options: [
      { id: 'a', text: 'Use larger Spot Instances so that each run finishes before an interruption is likely to happen.', why: "Interruptions can arrive at any time; a bigger instance shortens the window but doesn't make progress survive one." },
      { id: 'b', text: 'Request Spot Instances with a defined duration that covers the length of each run.', why: 'Spot blocks (defined-duration Spot) are no longer offered to new customers, and they would not save progress anyway.' },
      { id: 'c', text: 'Enable termination protection on the Spot Instances so EC2 cannot terminate them mid-run.', why: 'Termination protection guards against accidental API terminations. It does not stop EC2 from reclaiming Spot capacity.' },
      { id: 'd', text: 'Checkpoint progress to S3 regularly and on the two-minute notice, so a replacement resumes from it.', why: 'Correct. Spot gives a two-minute warning (instance metadata or an EventBridge event). Checkpointing turns an interruption into a short pause instead of a restart.' },
    ],
    correct: ['d'],
  },
  {
    id: 'q-rf-spot-4',
    domain: 'cost',
    concepts: ['ec2-spot', 'ec2-purchase-options'],
    difficulty: 3,
    stem: 'A web tier behind an Application Load Balancer needs at least 4 instances at all times and scales out to 20 at peak. The application is stateless. The company wants the lowest cost without risking the baseline capacity. Which Auto Scaling group configuration meets these requirements?',
    options: [
      { id: 'a', text: 'All instances On-Demand, covered by a Compute Savings Plan sized for the 20-instance peak.', why: "The plan would be idle most of the day: you pay the commitment whether or not 20 instances are running." },
      { id: 'b', text: 'An On-Demand base capacity of 4 with 100% Spot above it, across several instance types.', why: 'Correct. The base is always On-Demand, so the minimum never depends on Spot. Peak capacity comes from Spot, which suits a stateless tier and is the cheapest option for burst.' },
      { id: 'c', text: 'All instances Spot, using one instance type and the capacity-optimized allocation strategy.', why: 'A Spot crunch could take the group below the 4 instances the application needs.' },
      { id: 'd', text: 'An On-Demand base of 0 and 50% Spot above it, across several instance types.', why: 'With no base, half of every scale-out is Spot and the baseline itself can be interrupted. The requirement says the 4 must not be at risk.' },
    ],
    correct: ['b'],
  },

  // ----- The steady-state fleet (Savings Plans and Reserved Instances) -----
  {
    id: 'q-rf-sp-1',
    domain: 'cost',
    concepts: ['ec2-purchase-options'],
    difficulty: 2,
    stem: 'A company runs a steady compute load that will last at least three years. Over that time it plans to move part of the workload from EC2 to AWS Lambda and to change instance families. Which purchasing option gives the largest discount while staying applicable after these changes?',
    options: [
      { id: 'a', text: 'Standard Reserved Instances for the current instance family', why: 'Standard RIs can change size within a family, but not family. After the move they would bill for instances no longer running.' },
      { id: 'b', text: 'EC2 Instance Savings Plans', why: "An EC2 Instance Savings Plan is tied to one instance family in one Region and doesn't cover Lambda." },
      { id: 'c', text: 'Compute Savings Plans', why: 'Correct. A Compute Savings Plan applies across instance families, sizes, Regions, operating systems, AWS Fargate and AWS Lambda, so the commitment follows the roadmap.' },
      { id: 'd', text: 'Spot Instances', why: 'Spot is cheapest for interruptible work, but a steady production load that must stay up is the wrong fit, and Spot does not apply to Lambda.' },
    ],
    correct: ['c'],
  },
  {
    id: 'q-rf-sp-2',
    domain: 'cost',
    concepts: ['ec2-purchase-options'],
    difficulty: 2,
    stem: 'A company runs 10 m6i.xlarge instances 24 hours a day in eu-west-1 and is certain it will keep this exact family in this Region for three years. It wants the highest possible discount. Which option should it choose?',
    options: [
      { id: 'a', text: 'A 3-year EC2 Instance Savings Plan for m6i in eu-west-1', why: "Correct. Committing to one family in one Region earns a deeper discount than a Compute Savings Plan, and the company doesn't need the extra flexibility." },
      { id: 'b', text: 'A 1-year Compute Savings Plan covering any family and Region', why: 'A Compute Savings Plan trades some discount for flexibility the company says it will not use, and a 1-year term discounts less than a 3-year term.' },
      { id: 'c', text: 'On-Demand Capacity Reservations for the 10 instances', why: 'Capacity Reservations guarantee capacity in an AZ but are billed at On-Demand rates: no discount by themselves.' },
      { id: 'd', text: '3-year Convertible Reserved Instances for the 10 instances', why: 'Convertible RIs can be exchanged for other families, and that flexibility comes with a smaller discount than an instance-family commitment.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-rf-sp-3',
    domain: 'cost',
    concepts: ['ec2-purchase-options'],
    difficulty: 3,
    stem: "A company bought a Compute Savings Plan with a commitment of $10 per hour. Its eligible usage, priced at Savings Plan rates, has dropped to $6 per hour after part of the workload was retired. What happens to the company's bill?",
    options: [
      { id: 'a', text: 'The plan automatically shrinks to $6 per hour.', why: "A Savings Plan is a fixed hourly commitment for the whole term; it doesn't shrink when usage does." },
      { id: 'b', text: 'The unused $4 per hour carries over to the next hour.', why: 'Unused commitment is lost each hour; nothing carries over.' },
      { id: 'c', text: 'The company is charged only for actual usage at the Savings Plan rate.', why: 'The commitment is charged whether or not usage reaches it.' },
      { id: 'd', text: 'The company still pays $10 per hour, so $4 per hour is wasted commitment.', why: 'Correct. You pay the hourly commitment for the term. This is why commitments are sized to the steady floor of usage, not today\'s level or the peak.' },
    ],
    correct: ['d'],
  },
  {
    id: 'q-rf-sp-4',
    domain: 'performant',
    concepts: ['ecs-fargate', 'ec2-purchase-options'],
    difficulty: 2,
    stem: 'A team runs containerized microservices on Amazon ECS on a fleet of EC2 instances that it patches and scales itself. The team wants to stop managing servers, and the company has an existing Compute Savings Plan it wants to keep using. Which solution meets these requirements?',
    options: [
      { id: 'a', text: 'Move the services to Amazon ECS on AWS Fargate.', why: 'Correct. Fargate runs each task without servers to patch or scale, and Compute Savings Plans apply to Fargate usage as well as EC2 and Lambda.' },
      { id: 'b', text: 'Move the services to Amazon EKS with self-managed node groups.', why: 'Self-managed nodes are still EC2 instances the team patches and scales.' },
      { id: 'c', text: 'Move the services to Amazon EC2 Dedicated Instances.', why: 'Dedicated Instances are single-tenant hardware: the team still manages the servers.' },
      { id: 'd', text: 'Rewrite every service as an AWS Batch job.', why: 'Batch is for batch jobs, not long-running services behind load balancers, and a rewrite is far more work than needed.' },
    ],
    correct: ['a'],
  },

  // ----- The oversized database (right-sizing) -----
  {
    id: 'q-rf-db-1',
    domain: 'cost',
    concepts: ['db-right-sizing'],
    difficulty: 2,
    stem: 'An Amazon RDS for PostgreSQL db.r5.4xlarge Multi-AZ instance averages 7% CPU and peaks at 20% during the busiest hour. Freeable memory stays high, and Performance Insights shows no waits on I/O. What is the MOST cost-effective change?',
    options: [
      { id: 'a', text: 'Turn off Multi-AZ to halve the cost, since the instance is almost idle.', why: 'That removes automatic failover: it cuts cost by giving up a resilience requirement, not by removing waste.' },
      { id: 'b', text: 'Move to a smaller instance class, keep Multi-AZ, and watch the metrics after the change.', why: 'Correct. The metrics show the instance is several sizes too big. Downsizing keeps the same engine and availability and cuts the bill in proportion.' },
      { id: 'c', text: 'Add two read replicas so that each instance does less work during the busy hour.', why: 'Replicas add instances and cost. The problem is an oversized primary, not too much load.' },
      { id: 'd', text: 'Buy 3-year Reserved Instances for the current instance class to cut its hourly price.', why: 'Reserving an oversized instance locks in the waste for one to three years. Right-size first, then commit.' },
    ],
    correct: ['b'],
  },
  {
    id: 'q-rf-db-2',
    domain: 'performant',
    concepts: ['elasticache', 'db-right-sizing'],
    difficulty: 2,
    stem: 'A product catalog on Amazon RDS for MySQL serves the same few thousand product pages over and over. The database was scaled up twice to handle read traffic, and the data changes only a few times a day. Which solution reduces database load and cost?',
    options: [
      { id: 'a', text: 'Enable Multi-AZ on the database so that the standby also serves read traffic.', why: "The Multi-AZ standby doesn't serve reads in a Multi-AZ instance deployment: it adds cost and no read capacity." },
      { id: 'b', text: 'Increase the allocated storage on the database to raise its baseline IOPS.', why: 'The load is repeated reads of the same rows, which fit in memory. More IOPS treats a symptom at extra cost.' },
      { id: 'c', text: 'Add Amazon ElastiCache with lazy loading and a TTL, then scale the database back down.', why: 'Correct. Hot, rarely changing reads are what a cache is for: most requests are served from memory in under a millisecond, and the database only sees misses.' },
      { id: 'd', text: 'Move the database to a larger Graviton instance with more memory for its buffer pool.', why: 'Graviton improves price-performance, but a bigger instance still pays to answer the same query thousands of times.' },
    ],
    correct: ['c'],
  },
  {
    id: 'q-rf-db-3',
    domain: 'performant',
    concepts: ['aurora', 'db-right-sizing'],
    difficulty: 2,
    stem: 'A B2B application is idle at night and on weekends, but traffic is unpredictable during business hours and can jump tenfold within minutes. The database is an Amazon Aurora PostgreSQL provisioned cluster sized for the peak. How can the company lower cost without hurting performance during spikes?',
    options: [
      { id: 'a', text: 'Use Aurora Serverless v2 instances with an ACU range that covers both the idle level and the peak.', why: 'Correct. Serverless v2 adjusts capacity in fine-grained increments within seconds, so the cluster pays for idle-level capacity at night and still absorbs the spikes.' },
      { id: 'b', text: 'Stop the cluster every night and weekend with a scheduled script, and start it in the morning.', why: 'Stopping helps only for predictable idle windows, and the business-hours spikes still need peak-sized capacity all day.' },
      { id: 'c', text: 'Replace the cluster with a single-AZ Amazon RDS instance one size smaller than today.', why: 'That trades away availability and still cannot follow tenfold spikes.' },
      { id: 'd', text: 'Add Aurora Replicas during busy periods and remove them by hand after each spike.', why: 'Manual changes are too slow for spikes that arrive within minutes, and replicas take minutes to add.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-rf-db-4',
    domain: 'cost',
    concepts: ['aurora', 'db-right-sizing'],
    difficulty: 3,
    stem: 'An Amazon Aurora MySQL cluster runs a heavy, steady OLTP workload. Cost Explorer shows that I/O charges make up about 40% of the cluster\'s monthly cost. What is the MOST cost-effective change?',
    options: [
      { id: 'a', text: 'Move the cluster to Aurora Serverless v2.', why: 'Serverless v2 changes how compute is billed. It does nothing about per-request I/O charges for a steady workload.' },
      { id: 'b', text: 'Add more Aurora Replicas to spread the I/O.', why: 'Replicas share the same cluster storage; they add instance cost and do not reduce I/O charges.' },
      { id: 'c', text: 'Migrate to Amazon RDS for MySQL with Provisioned IOPS storage.', why: 'A migration is a large project with its own costs, and Aurora has a built-in option for exactly this situation.' },
      { id: 'd', text: 'Switch the cluster storage configuration to Aurora I/O-Optimized.', why: 'Correct. I/O-Optimized has no per-request I/O charges in exchange for higher instance and storage prices. AWS recommends it when I/O exceeds about a quarter of Aurora spend.' },
    ],
    correct: ['d'],
  },

  // ----- The photo archive (storage classes and lifecycle) -----
  {
    id: 'q-rf-s3-1',
    domain: 'cost',
    concepts: ['s3-intelligent-tiering'],
    difficulty: 2,
    stem: 'A photo-sharing app stores user photos in Amazon S3. Some photos are never viewed again after the first week, while others go viral years later. Access patterns cannot be predicted, and any photo must load in milliseconds. Which storage class is the MOST cost-effective?',
    options: [
      { id: 'a', text: 'S3 Standard', why: 'Standard serves everything fast but charges the highest storage rate for photos nobody opens.' },
      { id: 'b', text: 'S3 Intelligent-Tiering', why: 'Correct. Intelligent-Tiering moves each object between access tiers based on its own access, with no retrieval fees, and the automatic tiers all serve reads in milliseconds.' },
      { id: 'c', text: 'S3 Standard-Infrequent Access', why: 'Standard-IA charges a retrieval fee per GB. Viral old photos would be read heavily and cost more than in Standard.' },
      { id: 'd', text: 'S3 Glacier Flexible Retrieval', why: 'Retrievals take minutes to hours, which breaks the millisecond requirement.' },
    ],
    correct: ['b'],
  },
  {
    id: 'q-rf-s3-2',
    domain: 'cost',
    concepts: ['s3-lifecycle', 's3-storage-classes'],
    difficulty: 2,
    stem: 'A company generates report exports in Amazon S3. Each export is downloaded once within a day of creation and must be deleted after 14 days. What is the MOST cost-effective storage approach?',
    options: [
      { id: 'a', text: 'Store exports in S3 Standard-IA and transition them to S3 Glacier Deep Archive after 7 days.', why: 'Standard-IA bills a minimum of 30 days and Deep Archive a minimum of 180 days, so short-lived objects pay for storage long after they are deleted.' },
      { id: 'b', text: 'Store exports in S3 Intelligent-Tiering with a lifecycle rule to expire them after 14 days.', why: 'Intelligent-Tiering adds a per-object monitoring fee and only moves objects after 30 days without access, so it saves nothing on 14-day objects.' },
      { id: 'c', text: 'Store exports in S3 Standard with a lifecycle rule that expires objects after 14 days.', why: 'Correct. Standard has no minimum storage duration or retrieval fee, which suits short-lived, read-once data, and the expiration rule deletes them automatically.' },
      { id: 'd', text: 'Store exports in S3 One Zone-IA and delete them manually each month.', why: 'One Zone-IA also has a 30-day minimum and a retrieval fee, and manual monthly deletion breaks the 14-day rule.' },
    ],
    correct: ['c'],
  },
  {
    id: 'q-rf-s3-3',
    domain: 'secure',
    concepts: ['s3-lifecycle', 's3-versioning'],
    difficulty: 3,
    stem: 'A versioned S3 bucket has a lifecycle rule that expires current objects after 365 days. An audit finds that "expired" customer documents can still be restored a year later, which breaks the data-retention policy. What should a solutions architect add?',
    options: [
      { id: 'a', text: 'A lifecycle action that permanently deletes noncurrent versions after N days, plus removing expired delete markers.', why: 'Correct. In a versioned bucket, expiring the current version only adds a delete marker; the old version stays as a noncurrent version until a NoncurrentVersionExpiration action deletes it.' },
      { id: 'b', text: 'Turn on S3 Object Lock in compliance mode with a 365-day retention so that every version expires on schedule.', why: 'Object Lock prevents deletion. It would make the problem worse.' },
      { id: 'c', text: 'Suspend versioning on the bucket so the existing expiration rule permanently deletes objects from now on.', why: 'Suspending versioning stops new versions but leaves every existing noncurrent version in place.' },
      { id: 'd', text: 'Enable default encryption with SSE-KMS and schedule deletion of the KMS key after 365 days.', why: 'Deleting the key would make every object unreadable at once, current ones included, and key deletion can only be scheduled 7 to 30 days ahead. It is not a per-object retention rule.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-rf-s3-4',
    domain: 'cost',
    concepts: ['s3-intelligent-tiering'],
    difficulty: 3,
    stem: 'A company stores 400 million objects in S3 Intelligent-Tiering. Most objects are 20 KB thumbnails. The monthly storage cost did not go down after the move from S3 Standard, and the month of the move cost more than usual. What explains this?',
    options: [
      { id: 'a', text: 'Intelligent-Tiering charges a retrieval fee every time a thumbnail in one of its infrequent tiers is read.', why: 'Intelligent-Tiering has no retrieval fees for its automatic access tiers.' },
      { id: 'b', text: 'Objects under 128 KB stay in the Frequent Access tier, so thumbnails save nothing, and each move was billed per request.', why: "Correct. Small objects aren't eligible for auto-tiering and are charged at the Frequent Access rate, which matches S3 Standard, so they saved nothing, while hundreds of millions of requests cost money. Intelligent-Tiering pays off for larger objects with unknown access." },
      { id: 'c', text: 'Intelligent-Tiering stores objects in a single Availability Zone, which is billed at a premium over S3 Standard.', why: 'Intelligent-Tiering stores data across multiple AZs, like Standard.' },
      { id: 'd', text: 'Intelligent-Tiering has a 180-day minimum storage duration, so the first months are billed in full.', why: 'Intelligent-Tiering has no minimum storage duration charge.' },
    ],
    correct: ['b'],
  },

  // ----- The chatty AZ (cross-AZ and NAT costs) -----
  {
    id: 'q-rf-az-1',
    domain: 'cost',
    concepts: ['cross-az-costs', 'nat-data-processing'],
    difficulty: 2,
    stem: 'Application servers in two Availability Zones send all their internet-bound traffic through a single NAT gateway in the first AZ. The bill shows large NAT gateway data processing charges and inter-AZ data transfer. Which change reduces cost and also removes a single point of failure?',
    options: [
      { id: 'a', text: 'Move the NAT gateway to a larger size that has a lower per-GB processing rate.', why: "NAT gateways don't come in sizes; they scale automatically. This changes nothing." },
      { id: 'b', text: 'Replace the NAT gateway with a NAT instance in the first AZ to avoid the processing charge.', why: 'A NAT instance is still a single point of failure, now one you patch yourself, and traffic still crosses AZs.' },
      { id: 'c', text: 'Add a route to the internet gateway in the private subnets of the second AZ.', why: 'Instances without public IP addresses cannot use an internet gateway directly, and it would make the subnets public.' },
      { id: 'd', text: 'Create a NAT gateway in each AZ and route each private subnet to the one in its own AZ.', why: 'Correct. Traffic stays in its AZ, so the cross-AZ charge disappears, and losing one AZ no longer cuts the other off from the internet.' },
    ],
    correct: ['d'],
  },
  {
    id: 'q-rf-az-2',
    domain: 'resilient',
    concepts: ['nat-gateway', 'static-stability'],
    difficulty: 2,
    stem: 'During an Availability Zone outage, instances in the healthy AZ lost access to a third-party payment API on the internet, even though they kept running. What is the MOST likely cause?',
    options: [
      { id: 'a', text: 'The private subnets in both AZs routed internet traffic to a NAT gateway in the failed AZ.', why: 'Correct. A NAT gateway is a zonal resource. When its AZ fails, every subnet that routes through it loses outbound internet access.' },
      { id: 'b', text: 'The internet gateway was attached in the failed AZ and had no standby in the healthy one.', why: "An internet gateway isn't tied to an AZ; it is redundant across the VPC." },
      { id: 'c', text: 'The security groups of the healthy instances were reset to their defaults during the outage.', why: "An AZ outage doesn't change security groups, which are VPC-wide." },
      { id: 'd', text: "The VPC's main route table was stored in the failed AZ and was unavailable during the outage.", why: "Route tables aren't zonal; they belong to the VPC and are associated with subnets." },
    ],
    correct: ['a'],
  },
  {
    id: 'q-rf-az-3',
    domain: 'cost',
    concepts: ['vpc-gateway-endpoints', 'nat-data-processing'],
    difficulty: 1,
    stem: 'EC2 instances in private subnets read 50 TB per month from Amazon S3 in the same Region through a NAT gateway. What is the MOST cost-effective way to reduce this cost?',
    options: [
      { id: 'a', text: 'Enable S3 Transfer Acceleration on the bucket and use its endpoint.', why: 'Transfer Acceleration speeds up long-distance transfers over the internet and adds a charge.' },
      { id: 'b', text: 'Create an S3 gateway VPC endpoint and add it to the private subnets\' route tables.', why: 'Correct. Gateway endpoints for S3 and DynamoDB have no hourly or per-GB charge, so the traffic skips NAT data processing entirely.' },
      { id: 'c', text: 'Create an S3 interface endpoint (AWS PrivateLink) in each Availability Zone.', why: 'Interface endpoints work but charge per hour and per GB. The gateway endpoint does the same job for free.' },
      { id: 'd', text: 'Put Amazon CloudFront in front of the bucket so the instances read cached copies.', why: "The instances aren't internet users; CloudFront adds cost and the reads would still leave through the NAT gateway." },
    ],
    correct: ['b'],
  },
  {
    id: 'q-rf-az-4',
    domain: 'performant',
    concepts: ['elasticache', 'cross-az-costs'],
    difficulty: 3,
    stem: 'An application reads the same session and profile data from a database thousands of times per second. Latency must stay in single-digit milliseconds, and the data must survive the loss of a cache node. Which solution meets these requirements?',
    options: [
      { id: 'a', text: 'A node-based Amazon ElastiCache (Memcached) cluster with several nodes', why: "Node-based Memcached clusters have no replication: a lost node loses its data, which breaks the survival requirement." },
      { id: 'b', text: 'An Amazon S3 bucket in the S3 Standard storage class', why: 'S3 is durable but its request latency is far higher than an in-memory cache for this access rate.' },
      { id: 'c', text: 'Amazon ElastiCache (Redis OSS or Valkey) with a replica in another AZ and automatic failover', why: 'Correct. Reads come from memory in under a millisecond, and the replica in another AZ is promoted automatically if the primary fails.' },
      { id: 'd', text: 'An Amazon RDS read replica in the same AZ as the application, with a larger instance class', why: 'A replica offloads reads but is still a disk-backed database; it will not match an in-memory cache at thousands of reads per second.' },
    ],
    correct: ['c'],
  },

  // ===== Bank balancing: secure =====
  {
    id: 'q-s4-waf-1',
    domain: 'secure',
    concepts: ['aws-waf'],
    difficulty: 1,
    stem: 'A public website behind an Application Load Balancer is being hit by a bot that sends thousands of login requests per minute from a small set of IP addresses. Which solution blocks this traffic with the LEAST operational overhead?',
    options: [
      { id: 'a', text: 'Add deny rules for the IP addresses to the network ACL of the public subnets.', why: 'NACLs have a small rule limit and need manual updates every time the bot changes address.' },
      { id: 'b', text: 'Remove the inbound HTTPS rule from the ALB security group during attacks.', why: 'That blocks every user, not just the bot.' },
      { id: 'c', text: 'Run a script on the web servers to drop requests from busy IP addresses.', why: 'The traffic still reaches and loads the servers, and the script is custom code to maintain.' },
      { id: 'd', text: 'Associate an AWS WAF web ACL with a rate-based rule with the ALB.', why: 'Correct. A rate-based rule automatically blocks source IPs that exceed a request rate, before requests reach the servers.' },
    ],
    correct: ['d'],
  },
  {
    id: 'q-s4-waf-2',
    domain: 'secure',
    concepts: ['aws-waf', 'security-services'],
    difficulty: 2,
    stem: 'A company must protect a web application from SQL injection and cross-site scripting attacks and from large-scale DDoS attacks, with access to the AWS DDoS response team. The application runs behind Amazon CloudFront. Which combination meets these requirements? (Choose TWO.)',
    options: [
      { id: 'a', text: 'AWS WAF with AWS Managed Rules for SQL injection and XSS on the distribution', why: 'Correct. WAF inspects HTTP requests and its managed rule groups block common injection attacks at the edge.' },
      { id: 'b', text: 'AWS Shield Advanced on the distribution, with SRT access enabled', why: 'Correct. Shield Advanced adds enhanced DDoS detection and mitigation, cost protection, and access to the Shield Response Team.' },
      { id: 'c', text: 'Amazon GuardDuty with malware protection for the origin servers', why: 'GuardDuty detects threats from logs; it does not block web requests.' },
      { id: 'd', text: 'Amazon Inspector scanning the application servers continuously', why: 'Inspector scans workloads for software vulnerabilities; it does not filter traffic.' },
      { id: 'e', text: 'Security group rules on the origin that deny requests containing SQL keywords', why: 'Security groups filter by IP, port and protocol. They cannot inspect request content and have no deny rules.' },
    ],
    correct: ['a', 'b'],
  },
  {
    id: 'q-s4-pb-1',
    domain: 'secure',
    concepts: ['permissions-boundaries'],
    difficulty: 3,
    stem: 'Developers need to create IAM roles for their Lambda functions without being able to create roles that have more permissions than the developers have been allowed. What should a security engineer do?',
    options: [
      { id: 'a', text: 'Allow iam:CreateRole only when a set permissions boundary is attached, and deny removing it.', why: 'Correct. Every role the developers create is capped by the boundary: its effective permissions are the intersection of its policies and the boundary.' },
      { id: 'b', text: 'Give the developers AdministratorAccess and review the new roles in CloudTrail every week.', why: 'Weekly review finds an escalation after it has happened. It does not prevent it.' },
      { id: 'c', text: 'Attach an SCP to the account that denies iam:CreateRole and iam:AttachRolePolicy to everyone.', why: 'That stops developers creating any role, which they need to do.' },
      { id: 'd', text: 'Require MFA for the developers before they can call any IAM action that creates or changes roles.', why: 'MFA proves who the developer is; it does not limit what roles they can create.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-s4-pb-2',
    domain: 'secure',
    concepts: ['permissions-boundaries', 'iam-policy-evaluation'],
    difficulty: 2,
    stem: 'An IAM role has an identity-based policy that allows s3:* and dynamodb:*. Its permissions boundary allows s3:GetObject and sqs:SendMessage. Which actions can the role perform?',
    options: [
      { id: 'a', text: 's3:*, dynamodb:* and sqs:SendMessage', why: "A boundary never adds permissions. It only limits what the identity policy grants." },
      { id: 'b', text: 'Only s3:GetObject', why: 'Correct. The effective permissions are the intersection: s3:GetObject is the only action allowed by both the identity policy and the boundary.' },
      { id: 'c', text: 's3:GetObject and sqs:SendMessage', why: 'sqs:SendMessage is in the boundary but no identity policy allows it, so it is still denied.' },
      { id: 'd', text: 's3:* only', why: 'The boundary limits S3 to GetObject; the rest of s3:* is outside it.' },
    ],
    correct: ['b'],
  },
  {
    id: 'q-s4-scp-1',
    domain: 'secure',
    concepts: ['scps', 'aws-organizations'],
    difficulty: 2,
    stem: 'A company uses AWS Organizations. It must ensure that no one in any member account, including each account\'s root user, can launch resources outside us-east-1 and eu-west-1. Which solution meets this requirement?',
    options: [
      { id: 'a', text: 'Attach an IAM policy to every user and role in each account that denies actions in all other Regions.', why: "IAM policies can't restrict the root user, and every new user or role would need the policy." },
      { id: 'b', text: 'Configure AWS Config rules in every account to flag and delete resources launched in other Regions.', why: 'Config detects after the fact; it does not prevent the launch.' },
      { id: 'c', text: 'Attach an SCP that denies actions when aws:RequestedRegion is neither Region, exempting global services.', why: "Correct. SCPs set the maximum permissions for every principal in member accounts, including their root users. Global services such as IAM need an exemption because their requests aren't made in those Regions." },
      { id: 'd', text: 'Disable all other Regions under Account settings in the management account so the organization cannot use them.', why: 'Default Regions cannot be disabled, and this would not cover member accounts consistently.' },
    ],
    correct: ['c'],
  },
  {
    id: 'q-s4-scp-2',
    domain: 'secure',
    concepts: ['scps', 'iam-policy-evaluation'],
    difficulty: 3,
    stem: 'An SCP attached to an OU allows only ec2:* and s3:*. A user in an account in that OU has an IAM policy that allows dynamodb:PutItem. What happens when the user calls dynamodb:PutItem?',
    options: [
      { id: 'a', text: 'The call is denied, because the SCP does not allow DynamoDB actions.', why: 'Correct. An action must be allowed by the SCPs at every level and by the identity policy. SCPs never grant permissions; they only set the limit.' },
      { id: 'b', text: 'The call succeeds, because the IAM policy in the account explicitly allows it.', why: "IAM allows are filtered by the SCP. Outside the SCP's allow list, nothing in the account can grant the action." },
      { id: 'c', text: 'The call succeeds, because SCPs only affect the root user.', why: 'SCPs affect every IAM user and role in member accounts, including the root user.' },
      { id: 'd', text: 'The call succeeds only if the user signed in with MFA.', why: 'MFA has no effect on SCP evaluation unless a policy has an MFA condition.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-s4-igw-1',
    domain: 'secure',
    concepts: ['internet-gateway', 'vpc-public-private'],
    difficulty: 1,
    stem: 'An EC2 instance in a subnet that has a route of 0.0.0.0/0 to an internet gateway cannot be reached from the internet. Its security group allows inbound HTTPS from anywhere. What is the MOST likely cause?',
    options: [
      { id: 'a', text: 'The internet gateway is in a different Availability Zone.', why: 'Internet gateways are not zonal; one gateway serves every AZ in the VPC.' },
      { id: 'b', text: 'The instance has no public IPv4 address or Elastic IP address.', why: 'Correct. The internet gateway translates between public and private addresses. Without a public IP the instance has no internet-routable address.' },
      { id: 'c', text: 'The internet gateway has reached its bandwidth limit and drops new connections.', why: 'Internet gateways are horizontally scaled and have no bandwidth limit of their own.' },
      { id: 'd', text: 'Security groups need an outbound rule for the response.', why: 'Security groups are stateful: responses to allowed inbound traffic are allowed automatically.' },
    ],
    correct: ['b'],
  },
  {
    id: 'q-s4-sec-1',
    domain: 'secure',
    concepts: ['security-services'],
    difficulty: 1,
    stem: 'A company stores millions of documents in Amazon S3 and must find which buckets contain personally identifiable information such as passport numbers. Which service should it use?',
    options: [
      { id: 'a', text: 'Amazon GuardDuty', why: 'GuardDuty looks for threats in account activity and network logs, not for sensitive data inside objects.' },
      { id: 'b', text: 'AWS Shield', why: 'Shield protects against DDoS attacks.' },
      { id: 'c', text: 'Amazon Macie', why: 'Correct. Macie uses managed and custom data identifiers to discover sensitive data such as PII in S3.' },
      { id: 'd', text: 'Amazon Inspector', why: 'Inspector scans EC2 instances, container images and Lambda functions for vulnerabilities.' },
    ],
    correct: ['c'],
  },
  {
    id: 'q-s4-sec-2',
    domain: 'secure',
    concepts: ['security-services', 'encryption-at-rest'],
    difficulty: 2,
    stem: 'An application on EC2 connects to Amazon RDS with a database password stored in a configuration file. Security requires the password to be removed from the file and rotated automatically every 30 days. Which solution meets these requirements with the LEAST operational effort?',
    options: [
      { id: 'a', text: 'Store the password in AWS Secrets Manager with automatic rotation, and read it at runtime with an instance role.', why: 'Correct. Secrets Manager stores the secret encrypted with KMS and has built-in rotation for RDS credentials.' },
      { id: 'b', text: 'Store the password in an encrypted S3 object and rotate it with a cron job on the instance every 30 days.', why: 'That works but is custom code to build, secure and maintain.' },
      { id: 'c', text: 'Store the password as a plaintext environment variable in the instance user data.', why: 'User data is readable from the instance and the console, and nothing rotates it.' },
      { id: 'd', text: 'Encrypt the configuration file with an AWS KMS key and decrypt it when the application starts.', why: 'The password is still static: nothing rotates it.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-s4-kms-1',
    domain: 'secure',
    concepts: ['kms-key-policies'],
    difficulty: 3,
    stem: 'Account A has a customer managed KMS key that encrypts objects in an S3 bucket. A role in Account B must read and decrypt those objects. The bucket policy already grants the role s3:GetObject. Reads still fail with AccessDenied. What else is required?',
    options: [
      { id: 'a', text: "A key policy statement in Account A allowing Account B kms:Decrypt, plus kms:Decrypt in the role's IAM policy.", why: 'Correct. Cross-account use of a KMS key needs both sides: the key policy must trust the other account, and the other account must grant its principal the permission.' },
      { id: 'b', text: 'Only an IAM policy on the role in Account B that allows kms:Decrypt on the key ARN in Account A.', why: "The key policy is the primary control for a KMS key. If it doesn't allow Account B, no IAM policy in Account B can." },
      { id: 'c', text: 'Re-encrypt the objects with SSE-S3 so that S3 decrypts them for any principal that the bucket policy allows.', why: 'That would work around it but removes the customer managed key the company chose for control and auditing.' },
      { id: 'd', text: 'Enable S3 Cross-Region Replication to a bucket in Account B that uses its own KMS key.', why: 'Replication copies data. It does not fix the missing key permissions and adds cost.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-s4-vpce-1',
    domain: 'secure',
    concepts: ['vpc-endpoint-policies', 's3-bucket-policy'],
    difficulty: 2,
    stem: 'A company must ensure that a sensitive S3 bucket can be accessed only from its VPC, and that instances in that VPC cannot copy data to S3 buckets owned by other accounts. Which combination of controls meets these requirements? (Choose TWO.)',
    options: [
      { id: 'a', text: 'A bucket policy on the sensitive bucket that denies requests unless aws:SourceVpce matches the VPC endpoint', why: 'Correct. The bucket refuses any request that does not arrive through the endpoint.' },
      { id: 'b', text: "A VPC endpoint policy on the S3 gateway endpoint that allows access only to the company's own buckets", why: 'Correct. The endpoint policy limits which buckets traffic through the endpoint may reach, which blocks copying to outside buckets.' },
      { id: 'c', text: 'A security group rule that allows outbound traffic only to the S3 managed prefix list for the Region, on port 443', why: "That still lets instances reach every bucket in S3, including other accounts' buckets." },
      { id: 'd', text: 'S3 Block Public Access on the sensitive bucket and on the account that owns it', why: "Block Public Access stops public access, but doesn't restrict authenticated access to the VPC or stop copying elsewhere." },
      { id: 'e', text: 'Default encryption with SSE-KMS on the sensitive bucket, using a key only the VPC roles can use', why: 'A key policy limits which principals can decrypt, not where requests come from, and it does nothing to stop copying data to other buckets.' },
    ],
    correct: ['a', 'b'],
  },
  {
    id: 'q-s4-iam-1',
    domain: 'secure',
    concepts: ['iam-roles', 'ecs-fargate'],
    difficulty: 2,
    stem: 'A containerized application on Amazon ECS with AWS Fargate must write to an Amazon DynamoDB table. How should the application get credentials?',
    options: [
      { id: 'a', text: 'Store an IAM user access key in the container image.', why: 'Long-lived keys in an image are easy to leak and are never rotated.' },
      { id: 'b', text: "Add DynamoDB permissions to the task execution role.", why: 'The task execution role is used by ECS to pull images and send logs, not by your application code.' },
      { id: 'c', text: 'Pass an access key as a plaintext environment variable in the task definition.', why: 'Task definitions are readable by anyone who can describe them, and the key is long-lived.' },
      { id: 'd', text: 'Assign an IAM task role with DynamoDB permissions to the task definition.', why: 'Correct. The task role gives the containers temporary credentials that the AWS SDK picks up automatically.' },
    ],
    correct: ['d'],
  },

  // ===== Bank balancing: resilient =====
  {
    id: 'q-s4-xr-1',
    domain: 'resilient',
    concepts: ['rds-cross-region-replicas', 'dr-strategies'],
    difficulty: 2,
    stem: 'A company runs Amazon RDS for MySQL in us-east-1. It needs a disaster recovery copy in us-west-2 with an RPO of minutes, and wants to serve read traffic to West Coast users from that copy in normal operation. Which solution meets these requirements?',
    options: [
      { id: 'a', text: 'Copy the automated snapshots to us-west-2 every day and restore them there if needed.', why: 'A daily copy gives an RPO of up to a day and cannot serve reads.' },
      { id: 'b', text: 'Create a cross-Region read replica in us-west-2 and promote it during a disaster.', why: 'Correct. Asynchronous replication typically lags by seconds to minutes, the replica serves local reads every day, and it can be promoted to a standalone primary.' },
      { id: 'c', text: 'Enable Multi-AZ on the primary so a standby is kept in another location.', why: 'Multi-AZ stays within one Region and its standby does not serve reads.' },
      { id: 'd', text: 'Use AWS DataSync to copy the database files to us-west-2 hourly.', why: 'DataSync copies files and object storage; it cannot replicate a live RDS database.' },
    ],
    correct: ['b'],
  },
  {
    id: 'q-s4-xr-2',
    domain: 'resilient',
    concepts: ['rds-cross-region-replicas'],
    difficulty: 3,
    stem: "After a Regional outage, a company promotes its cross-Region RDS read replica in us-west-2. What must the company do for the application to use the promoted database?",
    options: [
      { id: 'a', text: 'Nothing; the primary endpoint in us-east-1 now points to the promoted replica.', why: "Promotion doesn't redirect the old Region's endpoint. That is how Multi-AZ failover behaves, not cross-Region promotion." },
      { id: 'b', text: 'Restore the promoted replica from its latest snapshot into a new instance so that it becomes writable.', why: 'A promoted replica is already a standalone writable database.' },
      { id: 'c', text: "Point the application at the promoted instance's endpoint (for example via Route 53), then rebuild replication.", why: 'Correct. The promoted instance keeps its own endpoint and no longer replicates; the application must be redirected and a new replica created for the next failover.' },
      { id: 'd', text: 'Enable Multi-AZ on the original primary so that the promoted replica becomes its standby in us-west-2.', why: 'The original primary is in the failed Region; changing it does not help.' },
    ],
    correct: ['c'],
  },
  {
    id: 'q-s4-fan-1',
    domain: 'resilient',
    concepts: ['messaging-fanout', 'sqs-dlq'],
    difficulty: 2,
    stem: 'When an order is placed, three independent services (billing, shipping and analytics) must each process it. If one service is down, the others must not be affected, and no order may be lost for the service that is down. Which design meets these requirements?',
    options: [
      { id: 'a', text: 'Publish orders to an Amazon SNS topic with an Amazon SQS queue subscribed for each service.', why: 'Correct. Fan-out: each service has its own durable queue, so a service that is down simply processes its backlog when it recovers.' },
      { id: 'b', text: 'Have the order service call each service synchronously over HTTPS and retry failed calls.', why: 'One service being down makes the order call fail or slow down for everyone.' },
      { id: 'c', text: 'Put orders on a single SQS standard queue that all three services poll for work.', why: 'Each message is delivered to only one consumer, so each order would reach one service, not all three.' },
      { id: 'd', text: 'Publish orders to an Amazon SNS topic with each service subscribed over HTTPS.', why: 'If an HTTPS subscriber is down for longer than the retry policy, messages are lost to it (unless a DLQ is set up); a queue per service holds them durably.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-s4-asg-1',
    domain: 'resilient',
    concepts: ['asg-health-checks', 'alb-health-checks'],
    difficulty: 2,
    stem: 'Instances in an Auto Scaling group behind an Application Load Balancer sometimes hang: the instance stays running but the application stops responding. The load balancer stops sending traffic to them, but they are never replaced. What should be changed?',
    options: [
      { id: 'a', text: 'Increase the ALB health check interval so hung instances are detected sooner.', why: 'A slower health check only takes longer to notice the problem.' },
      { id: 'b', text: 'Set the Auto Scaling group health check type to ELB.', why: 'Correct. With ELB health checks, the group treats an instance that fails the load balancer health check as unhealthy and replaces it.' },
      { id: 'c', text: 'Enable cross-zone load balancing.', why: 'That changes traffic distribution across AZs, not instance replacement.' },
      { id: 'd', text: 'Add a CloudWatch alarm on CPU utilization.', why: 'A hung application may have normal CPU, and an alarm alone replaces nothing.' },
    ],
    correct: ['b'],
  },
  {
    id: 'q-s4-ddb-1',
    domain: 'resilient',
    concepts: ['dynamodb-capacity', 'aws-backup'],
    difficulty: 2,
    stem: 'A developer accidentally ran a script that overwrote thousands of items in a DynamoDB table 20 minutes ago. The company needs to recover the table as it was just before the script ran. Which feature makes this possible if it was already enabled?',
    options: [
      { id: 'a', text: 'DynamoDB Streams', why: 'Streams keep 24 hours of changes for consumers, but rebuilding a table from them would be custom work.' },
      { id: 'b', text: 'DynamoDB global tables', why: 'Global tables replicate the bad writes to every Region within seconds.' },
      { id: 'c', text: 'DynamoDB Accelerator (DAX)', why: 'DAX is a read cache; it is not a backup.' },
      { id: 'd', text: 'Point-in-time recovery (PITR)', why: 'Correct. PITR restores the table to any second within the retention period (up to 35 days) into a new table.' },
    ],
    correct: ['d'],
  },
  {
    id: 'q-s4-backup-1',
    domain: 'resilient',
    concepts: ['aws-backup'],
    difficulty: 2,
    stem: 'A company must keep backups of its EBS volumes, RDS databases and DynamoDB tables for 7 years. Backups must be stored in a separate account and Region and must be impossible to delete, even for administrators. Which solution meets these requirements?',
    options: [
      { id: 'a', text: 'Use AWS Backup to copy to a vault in another account and Region, and lock that vault with Vault Lock in compliance mode.', why: 'Correct. AWS Backup centralizes backups across these services, cross-account and cross-Region copies isolate them, and Vault Lock in compliance mode makes them immutable for the retention period.' },
      { id: 'b', text: 'Write a Lambda function that snapshots all three services and copies the snapshots to S3 Glacier Deep Archive in another account.', why: 'Custom code across three services is a lot to maintain, and nothing stops an administrator deleting the copies.' },
      { id: 'c', text: 'Enable automated backups with 35-day retention on every database and export them to S3 every month.', why: 'Automated backups cover only RDS and stop at 35 days. Monthly exports are custom work, miss EBS, and nothing stops an administrator deleting them.' },
      { id: 'd', text: 'Use Amazon Data Lifecycle Manager policies for all three services with cross-account copy rules.', why: 'Data Lifecycle Manager manages EBS snapshots and AMIs only.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-s4-cw-1',
    domain: 'resilient',
    concepts: ['cloudwatch-metrics', 'sqs-visibility-timeout'],
    difficulty: 2,
    stem: 'Workers on an Auto Scaling group process messages from an SQS queue. During busy periods the backlog grows for hours because the group scales on CPU, which stays moderate. Which scaling approach keeps the backlog under control?',
    options: [
      { id: 'a', text: 'Target tracking on backlog per instance (visible messages divided by running instances).', why: 'Correct. Backlog per instance measures the actual work waiting, so the group grows as the queue grows regardless of CPU.' },
      { id: 'b', text: 'Lower the CPU target tracking value from 50% to 20% so the group scales out much earlier.', why: "If the work is I/O-bound, CPU stays low no matter how big the backlog is." },
      { id: 'c', text: 'Increase the queue visibility timeout so each worker has more time to finish its messages.', why: 'That changes how long a message stays hidden while being processed, not how many workers there are.' },
      { id: 'd', text: 'Add a scheduled action that doubles the group every morning and shrinks it again at night.', why: "Busy periods aren't on a fixed schedule here; a scheduled action would miss them or waste capacity." },
    ],
    correct: ['a'],
  },
  {
    id: 'q-s4-r53-1',
    domain: 'resilient',
    concepts: ['route53-routing-policies', 'dr-strategies'],
    difficulty: 1,
    stem: 'A company runs the same application in two Regions and wants to send each user to the Region with the lowest latency, while automatically removing a Region from responses if it becomes unhealthy. Which Route 53 configuration meets these requirements?',
    options: [
      { id: 'a', text: 'Geolocation routing with a record for each continent', why: 'Geolocation routes by where the user is, which is not always the lowest-latency Region.' },
      { id: 'b', text: 'Simple routing with both Regions as values in one record', why: 'Simple routing has no health checks and returns all values in random order.' },
      { id: 'c', text: 'Weighted routing with equal weights and health checks', why: 'Weighted routing splits traffic by percentage regardless of latency.' },
      { id: 'd', text: 'Latency-based routing with health checks on each record', why: 'Correct. Route 53 answers with the lowest-latency healthy Region and drops a Region whose health check fails.' },
    ],
    correct: ['d'],
  },
  {
    id: 'q-s4-ss-1',
    domain: 'resilient',
    concepts: ['static-stability', 'asg-scaling'],
    difficulty: 3,
    stem: 'An application needs 6 instances to serve peak load and runs in two Availability Zones. The company requires it to keep serving peak load if one AZ fails, without waiting for new instances to launch. How many instances should run?',
    options: [
      { id: 'a', text: '6 instances, 3 in each AZ, with Auto Scaling to replace lost capacity', why: 'After an AZ failure only 3 remain until replacements launch and warm up, which the requirement rules out.' },
      { id: 'b', text: '12 instances, 6 in each AZ', why: 'Correct. Each AZ alone can carry the peak, so losing one AZ needs no launches. This is static stability; with three AZs the same goal needs only 9 (3 per AZ).' },
      { id: 'c', text: '7 instances, 4 in one AZ and 3 in the other', why: 'Losing the AZ with 4 leaves 3, half of what peak needs.' },
      { id: 'd', text: '6 instances in a single AZ with a warm standby in the other', why: 'A standby that must scale up still has to launch capacity after the failure.' },
    ],
    correct: ['b'],
  },

  // ===== Bank balancing: performant =====
  {
    id: 'q-s4-ec-1',
    domain: 'performant',
    concepts: ['elasticache'],
    difficulty: 1,
    stem: 'A gaming company needs a real-time leaderboard that ranks millions of players by score and returns the top 100 in under a millisecond. Which solution is the best fit?',
    options: [
      { id: 'a', text: 'Amazon ElastiCache (Redis OSS or Valkey) using sorted sets', why: 'Correct. Sorted sets keep members ordered by score in memory, so ranking and top-N queries are fast at this scale.' },
      { id: 'b', text: 'Amazon RDS for MySQL with an index on the score column', why: 'An index helps, but a disk-backed relational query under constant writes will not reliably return in under a millisecond.' },
      { id: 'c', text: 'Amazon S3 with one object per player, listed and sorted by the app', why: 'Listing and sorting millions of objects takes seconds or minutes, nowhere near a millisecond.' },
      { id: 'd', text: 'Amazon ElastiCache (Memcached) with one key per player', why: 'Memcached is a simple key-value cache with no sorted data structures.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-s4-ec-2',
    domain: 'performant',
    concepts: ['elasticache'],
    difficulty: 2,
    stem: 'An application caches database query results in ElastiCache using lazy loading. Users sometimes see prices that are hours out of date after a product is updated. Which change fixes this while keeping the cache benefits?',
    options: [
      { id: 'a', text: 'Disable the cache for product reads and query the database directly for every price.', why: 'That removes the cache benefits entirely.' },
      { id: 'b', text: 'Increase the cache node size so that more product entries fit in memory at once.', why: 'A bigger node holds more data; it does not make stale data fresh.' },
      { id: 'c', text: 'Update or delete the cache entry whenever a product changes, and keep a TTL as a safety net.', why: 'Correct. Lazy loading alone serves whatever is cached until it expires. Writing through (or invalidating) on update keeps the cache current; the TTL bounds staleness if an update is missed.' },
      { id: 'd', text: 'Add read replicas to the cache cluster so that reads are spread across more nodes.', why: 'Replicas copy the same stale entries.' },
    ],
    correct: ['c'],
  },
  {
    id: 'q-s4-fg-1',
    domain: 'performant',
    concepts: ['ecs-fargate'],
    difficulty: 1,
    stem: 'A startup wants to run Docker containers for a web API without provisioning, patching or scaling any EC2 instances. Which solution meets these requirements?',
    options: [
      { id: 'a', text: 'Amazon ECS on EC2 with an Auto Scaling group', why: 'The team would still manage and patch the EC2 instances in the cluster.' },
      { id: 'b', text: 'AWS Elastic Beanstalk on a single EC2 instance', why: 'Beanstalk runs on EC2 instances that the account owns and that need updates.' },
      { id: 'c', text: 'Amazon EC2 with Docker installed', why: 'That is the most server management of all.' },
      { id: 'd', text: 'Amazon ECS on AWS Fargate', why: 'Correct. Fargate runs each task on infrastructure AWS manages; you specify only CPU and memory per task.' },
    ],
    correct: ['d'],
  },
  {
    id: 'q-s4-fg-2',
    domain: 'performant',
    concepts: ['ecs-fargate', 'ec2-spot'],
    difficulty: 2,
    stem: 'A company runs a containerized nightly data-processing job on Amazon ECS with AWS Fargate. The job can be restarted if interrupted. How can the company reduce its cost without managing servers?',
    options: [
      { id: 'a', text: 'Run the tasks with the Fargate Spot capacity provider.', why: 'Correct. Fargate Spot runs interruption-tolerant tasks on spare capacity at a steep discount, still with no servers to manage.' },
      { id: 'b', text: 'Move the job to EC2 On-Demand instances.', why: "That adds servers to manage and On-Demand EC2 isn't cheaper for an interruptible job." },
      { id: 'c', text: 'Give each task more vCPU so it finishes faster.', why: 'Fargate bills by vCPU and memory per second; doubling vCPU rarely halves the runtime, so cost usually rises.' },
      { id: 'd', text: 'Run the tasks on Dedicated Hosts registered with the cluster.', why: 'Dedicated Hosts are expensive and are servers to manage.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-s4-nlb-1',
    domain: 'performant',
    concepts: ['nlb-global-accelerator'],
    difficulty: 2,
    stem: 'A financial company exposes a TCP service on a custom port. Clients must allowlist fixed IP addresses in their firewalls, and the service needs very low latency at millions of requests per second. Which load balancer should the company use?',
    options: [
      { id: 'a', text: 'Application Load Balancer with a listener on the custom port', why: "An ALB handles HTTP and HTTPS at layer 7, and its IP addresses change, so they can't be allowlisted." },
      { id: 'b', text: 'Network Load Balancer with an Elastic IP address in each AZ', why: 'Correct. An NLB works at layer 4 for any TCP or UDP port, handles millions of requests per second with very low latency, and gives one static IP (optionally an Elastic IP) per AZ.' },
      { id: 'c', text: 'Classic Load Balancer with cross-zone load balancing enabled', why: 'The Classic Load Balancer is a previous-generation service without static IP addresses.' },
      { id: 'd', text: 'Gateway Load Balancer with the service instances as its targets', why: 'A Gateway Load Balancer distributes traffic to inline security appliances such as firewalls, not to an application.' },
    ],
    correct: ['b'],
  },
  {
    id: 'q-s4-ga-1',
    domain: 'performant',
    concepts: ['nlb-global-accelerator'],
    difficulty: 2,
    stem: 'A multiplayer game uses UDP and runs in us-east-1 and ap-southeast-1. Players worldwide complain of jittery connections, and the company wants regional failover within seconds without depending on DNS caching. Which solution meets these requirements?',
    options: [
      { id: 'a', text: 'Amazon CloudFront with both Regions as origins and origin failover between them', why: 'CloudFront serves HTTP and HTTPS, and WebSocket over HTTP. It does not carry raw UDP game traffic.' },
      { id: 'b', text: 'Route 53 latency-based routing with health checks and a 10-second TTL', why: 'DNS failover depends on clients and resolvers respecting TTLs, and the traffic still crosses the public internet the whole way.' },
      { id: 'c', text: 'AWS Global Accelerator with an endpoint group in each Region', why: 'Correct. Global Accelerator gives two static anycast IPs, carries TCP and UDP over the AWS backbone from the nearest edge, and shifts traffic between healthy endpoints in seconds without DNS changes.' },
      { id: 'd', text: 'An Application Load Balancer in each Region', why: 'ALBs are Regional and HTTP-only; they do not route UDP or route users between Regions.' },
    ],
    correct: ['c'],
  },
  {
    id: 'q-s4-ga-2',
    domain: 'performant',
    concepts: ['nlb-global-accelerator', 'cloudfront-edge'],
    difficulty: 3,
    stem: 'Which workload is a better fit for AWS Global Accelerator than for Amazon CloudFront?',
    options: [
      { id: 'a', text: 'Serving images and video segments to viewers in many countries from one Region', why: 'Cacheable HTTP content is what CloudFront is built for; serving it from edge caches beats any network path back to the origin.' },
      { id: 'b', text: 'A static website hosted in an S3 bucket with a custom domain name', why: 'A static site is ideal for CloudFront with origin access control.' },
      { id: 'c', text: 'Caching API responses at the edge so repeat requests skip the origin', why: "Global Accelerator doesn't cache anything; CloudFront does." },
      { id: 'd', text: 'A non-HTTP TCP service that needs static IPs and fast failover between Regions', why: 'Correct. Global Accelerator proxies TCP and UDP at the network layer with static anycast IPs. CloudFront is an HTTP cache.' },
    ],
    correct: ['d'],
  },
  {
    id: 'q-s4-aur-1',
    domain: 'performant',
    concepts: ['aurora', 'rds-read-replicas'],
    difficulty: 2,
    stem: 'An Aurora MySQL cluster has one writer and three Aurora Replicas. Reporting queries from a BI tool are slowing down the writer. How should the BI tool connect?',
    options: [
      { id: 'a', text: 'To the cluster endpoint, which always points at the current writer', why: 'That is what puts the reporting load on the writer today.' },
      { id: 'b', text: 'To the reader endpoint, which load-balances connections across the replicas', why: 'Correct. The reader endpoint spreads read-only connections across the replicas, which share the cluster storage, so the writer is left for writes.' },
      { id: 'c', text: 'To the instance endpoint of the writer, with a lower connection priority', why: "There is no priority setting on a connection: the writer's instance endpoint still sends every query to the writer." },
      { id: 'd', text: 'To a new cross-Region read replica created just for reporting', why: 'That adds cross-Region latency and cost when local replicas already exist.' },
    ],
    correct: ['b'],
  },
  {
    id: 'q-s4-aur-2',
    domain: 'performant',
    concepts: ['aurora'],
    difficulty: 2,
    stem: 'A company is moving a MySQL database that needs high throughput, up to 15 low-latency read replicas, and storage that grows automatically. Which option meets these requirements with the LEAST administration?',
    options: [
      { id: 'a', text: 'MySQL on EC2 with EBS io2 volumes', why: 'Self-managed MySQL needs patching, backups, replication and storage growth handled by the team.' },
      { id: 'b', text: 'Amazon RDS for MySQL with storage autoscaling', why: 'RDS for MySQL supports up to 15 read replicas but replicates asynchronously to separate storage, so replica lag is typically higher than Aurora, whose replicas share the cluster volume.' },
      { id: 'c', text: 'Amazon Aurora MySQL', why: 'Correct. Aurora keeps six copies of the data across three AZs, grows storage automatically, and supports up to 15 replicas that share the cluster volume with typically low replica lag.' },
      { id: 'd', text: 'Amazon DynamoDB', why: 'DynamoDB is a key-value database; a MySQL application would need to be rewritten.' },
    ],
    correct: ['c'],
  },
  {
    id: 'q-s4-proxy-1',
    domain: 'performant',
    concepts: ['lambda-concurrency', 'aurora'],
    difficulty: 2,
    stem: 'A Lambda function connects to an Amazon Aurora PostgreSQL database. During traffic spikes, thousands of concurrent invocations exhaust the database connections and requests fail. Which solution fixes this with the LEAST code change?',
    options: [
      { id: 'a', text: 'Put Amazon RDS Proxy between the function and the database.', why: 'Correct. RDS Proxy pools and shares database connections across invocations, so a spike in Lambda concurrency does not become a spike in database connections.' },
      { id: 'b', text: 'Increase the Lambda function memory so each invocation finishes faster.', why: "More memory makes each invocation faster but doesn't reduce how many connect at once." },
      { id: 'c', text: 'Move the function into a public subnet with a route to the database endpoint.', why: 'Network placement has nothing to do with the database connection limit.' },
      { id: 'd', text: 'Raise the reserved concurrency of the function to cover the spikes.', why: 'More concurrent invocations open even more database connections, which is the problem.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-s4-kds-1',
    domain: 'performant',
    concepts: ['kinesis-data-streams'],
    difficulty: 3,
    stem: 'A Kinesis data stream with 10 shards feeds five different consumer applications that all read the full stream. Consumers fall behind because they share each shard\'s read throughput. What is the MOST effective fix?',
    options: [
      { id: 'a', text: 'Register the consumers for enhanced fan-out.', why: 'Correct. Enhanced fan-out gives each registered consumer its own 2 MB per second per shard, pushed to it, instead of sharing one 2 MB per second among all readers.' },
      { id: 'b', text: 'Increase the stream retention period.', why: 'Longer retention lets consumers catch up later but does not make them read faster.' },
      { id: 'c', text: 'Replace the stream with an SQS standard queue.', why: 'A queue delivers each message to one consumer, not to all five.' },
      { id: 'd', text: 'Use Amazon Data Firehose instead of the consumers.', why: 'Firehose delivers to storage and analytics destinations; it does not replace five custom applications.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-s4-cf-1',
    domain: 'performant',
    concepts: ['cloudfront-edge', 'data-transfer-costs'],
    difficulty: 1,
    stem: 'A news site on EC2 serves the same articles and images to millions of readers worldwide, and the servers are overloaded during breaking news. Which solution improves performance for readers and reduces load on the servers?',
    options: [
      { id: 'a', text: 'Move the web servers to larger instance types and raise the Auto Scaling maximum.', why: 'Bigger servers still serve every request, and readers far from the Region still wait.' },
      { id: 'b', text: 'Put an Amazon CloudFront distribution in front of the site with suitable cache TTLs.', why: 'Correct. Edge locations serve cached copies close to readers, and most requests never reach the servers.' },
      { id: 'c', text: 'Enable Multi-AZ on the database so a standby can share the load during spikes.', why: 'Multi-AZ adds availability, not capacity for web requests.' },
      { id: 'd', text: 'Enable S3 Transfer Acceleration and serve the images from an S3 bucket.', why: 'Transfer Acceleration speeds up uploads to S3; it does not cache content for readers.' },
    ],
    correct: ['b'],
  },

  // ===== Bank balancing: cost =====
  {
    id: 'q-s4-cost-1',
    domain: 'cost',
    concepts: ['ec2-purchase-options'],
    difficulty: 1,
    stem: 'A team runs a development environment on EC2 only from 9 AM to 6 PM on weekdays, with unpredictable start and stop times during that window. Which option lowers cost the MOST with no commitment?',
    options: [
      { id: 'a', text: 'Buy 3-year Standard Reserved Instances for the development instances.', why: 'A commitment for 24 hours a day is wasted on a machine that runs about a quarter of the week.' },
      { id: 'b', text: 'Move the instances to Dedicated Instances so they are billed per second.', why: 'Dedicated Instances cost more than shared tenancy.' },
      { id: 'c', text: 'Stop the instances outside working hours, for example with Instance Scheduler.', why: 'Correct. Stopped instances pay only for EBS storage. Running roughly 45 of 168 hours cuts compute cost by about 70% with no commitment.' },
      { id: 'd', text: 'Use larger instances so that daily work finishes sooner and they run fewer hours.', why: 'A development environment is used interactively; bigger instances cost more per hour.' },
    ],
    correct: ['c'],
  },
  {
    id: 'q-s4-cost-2',
    domain: 'cost',
    concepts: ['data-transfer-costs', 'cross-az-costs'],
    difficulty: 2,
    stem: 'Which data transfer is free of charge?',
    options: [
      { id: 'a', text: 'Data from an EC2 instance to another EC2 instance in a different Availability Zone, using private IP addresses', why: 'Traffic between AZs is charged in each direction, even on private addresses.' },
      { id: 'b', text: 'Data from Amazon S3 to the internet', why: 'Data transfer out to the internet is charged (after a small monthly free allowance).' },
      { id: 'c', text: 'Data between two AWS Regions', why: 'Inter-Region data transfer is charged.' },
      { id: 'd', text: 'Data transferred into AWS from the internet', why: 'Correct. Inbound data transfer from the internet is free; you pay for what leaves.' },
    ],
    correct: ['d'],
  },
  {
    id: 'q-s4-cost-3',
    domain: 'cost',
    concepts: ['s3-storage-classes', 's3-lifecycle'],
    difficulty: 2,
    stem: 'Compliance requires a company to keep scanned contracts for 10 years. They are read often for the first 30 days, then almost never, and when one is needed an audit can wait up to 12 hours. What is the MOST cost-effective approach?',
    options: [
      { id: 'a', text: 'Keep the contracts in S3 Standard for 10 years and expire them with a lifecycle rule.', why: 'Standard charges the highest storage rate for data nobody reads.' },
      { id: 'b', text: 'Use a lifecycle rule to move objects to S3 Glacier Deep Archive after 30 days and expire them at 10 years.', why: 'Correct. Deep Archive is the lowest-cost class, its standard retrievals finish within 12 hours, and the 180-day minimum is irrelevant for 10-year data.' },
      { id: 'c', text: 'Store the contracts in S3 One Zone-IA from day one and expire them after 10 years.', why: 'One Zone-IA costs more than Deep Archive and loses the data if its AZ is destroyed, which is risky for compliance records.' },
      { id: 'd', text: 'Move the contracts to S3 Glacier Instant Retrieval after 30 days and keep them there for 10 years.', why: 'Instant Retrieval charges more for storage to offer millisecond access the audit does not need.' },
    ],
    correct: ['b'],
  },
  {
    id: 'q-s4-cost-4',
    domain: 'cost',
    concepts: ['db-right-sizing', 'dynamodb-capacity'],
    difficulty: 2,
    stem: 'A DynamoDB table uses provisioned capacity sized for a short daily peak. For 22 hours a day, consumed capacity is under 10% of what is provisioned. Traffic grows gradually and predictably. What is the MOST cost-effective change?',
    options: [
      { id: 'a', text: 'Enable DynamoDB auto scaling on the table with a target utilization.', why: 'Correct. Auto scaling adjusts provisioned capacity to follow the daily curve, so the table stops paying for peak capacity all day.' },
      { id: 'b', text: 'Add a global secondary index to spread the peak load across partitions.', why: 'An index adds its own capacity and storage cost and does not address over-provisioning.' },
      { id: 'c', text: 'Turn on DAX so that reads during the peak are served from a cache.', why: 'DAX caches reads but adds cluster cost; the waste here is unused provisioned capacity.' },
      { id: 'd', text: 'Buy DynamoDB reserved capacity at the peak level to lower its hourly price.', why: 'Reserving peak capacity locks in the over-provisioning for a year or more. Right-size with auto scaling first.' },
    ],
    correct: ['a'],
  },
  {
    id: 'q-s4-cost-5',
    domain: 'cost',
    concepts: ['cross-az-costs'],
    difficulty: 3,
    stem: 'A chatty microservice in us-east-1a calls a cache cluster node in us-east-1b millions of times per hour, generating large inter-AZ data transfer charges. The service runs in both AZs. Which change reduces this cost while keeping the design highly available?',
    options: [
      { id: 'a', text: 'Move every service instance and the cache cluster into us-east-1a so that all calls stay in one AZ.', why: 'That removes the charge by giving up AZ resilience.' },
      { id: 'b', text: 'Route the calls through a NAT gateway in each AZ so the traffic is billed as processing instead.', why: 'NAT adds a per-GB processing charge and still crosses AZs.' },
      { id: 'c', text: 'Create a VPC peering connection between the subnets in the two AZs to carry the cache traffic.', why: 'Subnets in the same VPC already route to each other; peering is for separate VPCs and does not change AZ transfer pricing.' },
      { id: 'd', text: 'Keep cache nodes in both AZs and read from the node in your own AZ, failing over only when needed.', why: 'Correct. Reads stay inside the AZ, which is free, and the other AZ still holds a node if one fails.' },
    ],
    correct: ['d'],
  },
  {
    id: 'q-s4-cost-6',
    domain: 'cost',
    concepts: ['ec2-spot', 'ec2-purchase-options'],
    difficulty: 1,
    stem: 'Which workload is the BEST fit for EC2 Spot Instances?',
    options: [
      { id: 'a', text: 'A single-instance relational database that backs a production application', why: 'An interruption would take the database down; databases need steady capacity.' },
      { id: 'b', text: 'A stateless image-rendering fleet that pulls jobs from a queue and can retry any job', why: 'Correct. Interruptions only delay individual jobs, which go back on the queue. This is the textbook Spot workload.' },
      { id: 'c', text: 'A licensed application whose license is tied to a specific physical server', why: 'Per-server licensing needs Dedicated Hosts, not Spot.' },
      { id: 'd', text: 'A payment API that must answer every request within 100 ms, around the clock', why: 'Losing capacity with two minutes of warning would break the latency commitment unless a stable base covers it.' },
    ],
    correct: ['b'],
  },
];
