import type { Concept } from '../engine/model';

// Concept IDs mapped to SAA-C03 task statements (Domain 1: 30%, 2: 26%, 3: 24%, 4: 20%).
export const CONCEPTS: Concept[] = [
  { id: 's3-block-public-access', title: 'S3 Block Public Access', domain: 'secure', task: '1.3' },
  { id: 's3-bucket-policy', title: 'S3 bucket policies', domain: 'secure', task: '1.1' },
  { id: 'cloudfront-oac', title: 'CloudFront Origin Access Control', domain: 'secure', task: '1.2' },
  { id: 'cloudfront-edge', title: 'CloudFront edge caching', domain: 'performant', task: '3.4' },
  { id: 'route53-alias', title: 'Route 53 alias records', domain: 'performant', task: '3.4' },
  { id: 'vpc-public-private', title: 'Public vs. private subnets', domain: 'secure', task: '1.2' },
  { id: 'internet-gateway', title: 'Internet gateways', domain: 'secure', task: '1.2' },
  { id: 'nat-gateway', title: 'NAT gateways', domain: 'resilient', task: '2.2' },
  { id: 'security-groups', title: 'Security groups', domain: 'secure', task: '1.2' },
  { id: 'nacls', title: 'Network ACLs', domain: 'secure', task: '1.2' },
  { id: 'sg-chaining', title: 'Security group chaining', domain: 'secure', task: '1.2' },
  { id: 'alb', title: 'Application Load Balancer', domain: 'resilient', task: '2.2' },
  { id: 'alb-health-checks', title: 'Target group health checks', domain: 'resilient', task: '2.2' },
  { id: 'asg-scaling', title: 'Auto Scaling policies and warmup', domain: 'performant', task: '3.2' },
  { id: 'static-stability', title: 'Static stability', domain: 'resilient', task: '2.2' },
  { id: 'rds-multi-az', title: 'RDS Multi-AZ', domain: 'resilient', task: '2.2' },
  { id: 'rds-backups', title: 'RDS backups and point-in-time restore', domain: 'resilient', task: '2.2' },
  { id: 'rds-read-replicas', title: 'RDS read replicas', domain: 'performant', task: '3.3' },
  { id: 'aws-waf', title: 'AWS WAF', domain: 'secure', task: '1.2' },
  { id: 'encryption-at-rest', title: 'Encryption at rest', domain: 'secure', task: '1.3' },
  { id: 'sqs-visibility-timeout', title: 'SQS visibility timeout', domain: 'resilient', task: '2.1' },
  { id: 'sqs-dlq', title: 'SQS dead-letter queues', domain: 'resilient', task: '2.1' },
  { id: 'lambda-concurrency', title: 'Lambda concurrency', domain: 'performant', task: '3.2' },
  { id: 'apigw-integrations', title: 'API Gateway integrations and limits', domain: 'resilient', task: '2.1' },
  { id: 'dynamodb-capacity', title: 'DynamoDB capacity modes', domain: 'performant', task: '3.3' },
  { id: 'vpc-gateway-endpoints', title: 'VPC gateway endpoints', domain: 'cost', task: '4.4' },
  { id: 'nat-data-processing', title: 'NAT gateway data processing charges', domain: 'cost', task: '4.4' },
  { id: 'data-transfer-costs', title: 'Data transfer pricing', domain: 'cost', task: '4.4' },
  // Stage 2: investigation, IAM and troubleshooting.
  { id: 'iam-policy-evaluation', title: 'IAM policy evaluation logic', domain: 'secure', task: '1.1' },
  { id: 'resource-vs-identity-policies', title: 'Identity-based vs. resource-based policies', domain: 'secure', task: '1.1' },
  { id: 'iam-roles', title: 'IAM roles, instance profiles and AssumeRole', domain: 'secure', task: '1.1' },
  { id: 'iam-condition-keys', title: 'IAM condition keys', domain: 'secure', task: '1.1' },
  { id: 'permissions-boundaries', title: 'Permissions boundaries', domain: 'secure', task: '1.1' },
  { id: 'scps', title: 'Service control policies (SCPs)', domain: 'secure', task: '1.1' },
  { id: 'kms-key-policies', title: 'KMS key policies', domain: 'secure', task: '1.3' },
  { id: 'vpc-endpoint-policies', title: 'VPC endpoint policies and aws:SourceVpce', domain: 'secure', task: '1.2' },
  { id: 'sg-vs-nacl', title: 'Security groups vs. network ACLs', domain: 'secure', task: '1.2' },
  { id: 'vpc-flow-logs', title: 'VPC Flow Logs', domain: 'secure', task: '1.2' },
  { id: 'cloudtrail', title: 'AWS CloudTrail', domain: 'secure', task: '1.1' },
  { id: 'alb-error-codes', title: 'ALB error codes (502 / 503 / 504)', domain: 'resilient', task: '2.2' },
  { id: 'asg-health-checks', title: 'Auto Scaling health checks', domain: 'resilient', task: '2.2' },
  { id: 'route-blackholes', title: 'Route tables and blackhole routes', domain: 'resilient', task: '2.2' },
  { id: 'cloudwatch-metrics', title: 'CloudWatch metrics for troubleshooting', domain: 'resilient', task: '2.2' },
  // ----- Stage 3: breadth -----
  { id: 'dr-strategies', title: 'DR strategies: backup and restore to multi-site', domain: 'resilient', task: '2.2' },
  { id: 'route53-routing-policies', title: 'Route 53 routing policies and health checks', domain: 'resilient', task: '2.2' },
  { id: 'rds-cross-region-replicas', title: 'RDS cross-Region read replicas', domain: 'resilient', task: '2.2' },
  { id: 'aurora', title: 'Amazon Aurora', domain: 'performant', task: '3.3' },
  { id: 'aurora-global', title: 'Aurora Global Database', domain: 'resilient', task: '2.2' },
  { id: 'dynamodb-global-tables', title: 'DynamoDB global tables', domain: 'resilient', task: '2.2' },
  { id: 'dax', title: 'DynamoDB Accelerator (DAX)', domain: 'performant', task: '3.3' },
  { id: 'aws-backup', title: 'AWS Backup', domain: 'resilient', task: '2.2' },
  { id: 'vpc-peering', title: 'VPC peering', domain: 'performant', task: '3.4' },
  { id: 'transit-gateway', title: 'AWS Transit Gateway', domain: 'performant', task: '3.4' },
  { id: 'site-to-site-vpn', title: 'AWS Site-to-Site VPN', domain: 'secure', task: '1.2' },
  { id: 'direct-connect', title: 'AWS Direct Connect', domain: 'performant', task: '3.4' },
  { id: 'hybrid-connectivity', title: 'Hybrid connectivity patterns', domain: 'resilient', task: '2.2' },
  { id: 'aws-organizations', title: 'AWS Organizations, accounts and RAM', domain: 'secure', task: '1.1' },
  { id: 's3-storage-classes', title: 'S3 storage classes', domain: 'cost', task: '4.1' },
  { id: 's3-lifecycle', title: 'S3 Lifecycle rules', domain: 'cost', task: '4.1' },
  { id: 's3-versioning', title: 'S3 Versioning and MFA Delete', domain: 'secure', task: '1.3' },
  { id: 's3-object-lock', title: 'S3 Object Lock (WORM)', domain: 'secure', task: '1.3' },
  { id: 's3-replication', title: 'S3 replication (CRR / SRR)', domain: 'resilient', task: '2.2' },
  { id: 'kinesis-data-streams', title: 'Kinesis Data Streams', domain: 'performant', task: '3.5' },
  { id: 'kinesis-firehose', title: 'Amazon Data Firehose', domain: 'performant', task: '3.5' },
  { id: 'athena-glue', title: 'Athena, Glue and the data lake', domain: 'performant', task: '3.5' },
  { id: 'messaging-fanout', title: 'Fan-out: SNS, SQS, EventBridge, Kinesis', domain: 'resilient', task: '2.1' },
  { id: 'snow-family', title: 'AWS Snow Family', domain: 'performant', task: '3.5' },
  { id: 'datasync', title: 'AWS DataSync and Storage Gateway', domain: 'performant', task: '3.1' },
  { id: 'dms', title: 'AWS Database Migration Service', domain: 'performant', task: '3.3' },
  { id: 'data-migration', title: 'Choosing a migration method', domain: 'performant', task: '3.5' },
  { id: 'block-file-storage', title: 'EBS, EFS and FSx', domain: 'performant', task: '3.1' },
  { id: 'security-services', title: 'Shield, GuardDuty, Macie, Inspector, Secrets Manager', domain: 'secure', task: '1.2' },
  // ----- Stage 4: refactors and the rest of the exam guide -----
  { id: 'ec2-spot', title: 'EC2 Spot Instances', domain: 'cost', task: '4.2' },
  { id: 'ec2-purchase-options', title: 'Savings Plans and Reserved Instances', domain: 'cost', task: '4.2' },
  { id: 'db-right-sizing', title: 'Right-sizing databases', domain: 'cost', task: '4.3' },
  { id: 's3-intelligent-tiering', title: 'S3 Intelligent-Tiering', domain: 'cost', task: '4.1' },
  { id: 'cross-az-costs', title: 'Cross-AZ traffic and AZ affinity', domain: 'cost', task: '4.4' },
  { id: 'elasticache', title: 'ElastiCache and caching strategies', domain: 'performant', task: '3.3' },
  { id: 'ecs-fargate', title: 'Containers: ECS, EKS and Fargate', domain: 'performant', task: '3.2' },
  { id: 'nlb-global-accelerator', title: 'NLB, Gateway Load Balancer and Global Accelerator', domain: 'performant', task: '3.4' },
];

/** SAA-C03 task statements (exam guide, 2026). */
export const TASKS: { id: string; domain: Concept['domain']; title: string }[] = [
  { id: '1.1', domain: 'secure', title: 'Design secure access to AWS resources' },
  { id: '1.2', domain: 'secure', title: 'Design secure workloads and applications' },
  { id: '1.3', domain: 'secure', title: 'Determine appropriate data security controls' },
  { id: '2.1', domain: 'resilient', title: 'Design scalable and loosely coupled architectures' },
  { id: '2.2', domain: 'resilient', title: 'Design highly available and/or fault-tolerant architectures' },
  { id: '3.1', domain: 'performant', title: 'Determine high-performing and/or scalable storage solutions' },
  { id: '3.2', domain: 'performant', title: 'Design high-performing and elastic compute solutions' },
  { id: '3.3', domain: 'performant', title: 'Determine high-performing database solutions' },
  { id: '3.4', domain: 'performant', title: 'Determine high-performing and/or scalable network architectures' },
  { id: '3.5', domain: 'performant', title: 'Determine high-performing data ingestion and transformation solutions' },
  { id: '4.1', domain: 'cost', title: 'Design cost-optimized storage solutions' },
  { id: '4.2', domain: 'cost', title: 'Design cost-optimized compute solutions' },
  { id: '4.3', domain: 'cost', title: 'Design cost-optimized database solutions' },
  { id: '4.4', domain: 'cost', title: 'Design a cost-optimized network architecture' },
];

export const CONCEPT_BY_ID: Record<string, Concept> = Object.fromEntries(CONCEPTS.map((c) => [c.id, c]));
